### ISSUE TITLE
Accessing data on external servers from UCloud

### ISSUE THREAD

**Issue by emolinaro** [SDU-eScience/UCloud#1002]
Today during the presentation of SDUCloud at the BMB meeting it was pretty clear that the main concern from people in using our platform is the fact that they are not willing to move their large amount of data from their local server to ours. That's also because their sequential machine constantly produces new data and it is not practical for them to move it every time. Some, indeed, asked if it would be possible to mount their data directly form the local server, avoiding to copy it on SDUCloud.

Actually, we heard the same concern from other people that are currently processing a large amount of data with ABACUS. They don't use the software on our platform because they don't want to move terabytes of data.

We should open a discussion about practical solutions to encourage these people to use our platform.

**Comment by DanThrane** [comment]
I believe this issue is no longer relevant given the work we are doing with external providers. The solution proposed by Claudio is more or less the design we are going with.
