### ISSUE TITLE
Project Role - eScience Center Support

### ISSUE THREAD

**Issue by bhjakobsen** [SDU-eScience/UCloud#1493]
Oprindeligt havde jeg tænkt på yderligere rolle “eScience Center Support” i et projekt.

Det kunne være Emiliano, Federica eller Henrik som bistår et projekt med at få placeret data og oprettet brugere mv i uCloud.

Opgaven vil være beskrevet i et issue.

Rettigheder skal være de samme som “Admin”.

**Comment by DanThrane** [comment]
Will reopen if we find some concrete use-cases.
