### ISSUE TITLE
Users should be able to delete their user

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#1495]
This should take into consideration all the information we have on that user, and not only delete the user from the system but all that is connected to the user.

- shares
- jobs
- files?
- etc.

Idea to design: Endpoint in auth to delete user. New service with dependency to all relevant services. Authstream Delete event created on deletion and picked up by new service.

**Comment by DanThrane** [comment]
Design changes in 2021.3.0 takes care of this.
