### ISSUE TITLE
[storage] Additional File sensitivity classification

### ISSUE THREAD

**Issue by bhjakobsen** [SDU-eScience/UCloud#1842]
The GDPR security model relies on the PI and the fact that he/she/? is responsible for that data is classified according to the law.

So it would be appropriate that the PI got a chance to approve the classification when data is included.

My suggestion is that when new data flows into the project it will be marked "**under review**" and locked until the the PI confirms the initial classification made by the project member.

**Comment by DanThrane** [comment]
I believe some version of this will be coming in a later version. We will investigate this as part of the file orchestrator epic. We probably won't be able to lock the data but we will almost certainly be able to mark it as under review.
