### ISSUE TITLE
App delete does not remove from elastic

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#1958]
This is seen on dev so assume it is also a problem on production.
They are deleted from postgres but does not seem to be deleted from elastic. This results in duplicates when searching for an app.
It does not throw any errors in the logs.

**Comment by DanThrane** [comment]
I think we should strongly consider deprecating application removal. It only causes issues, instead we should make it impossible to use these apps.

**Comment by hschu12** [comment]
Fine with me - this was also only used to remove test apps. The main idea of versions was of course that we should always keep old version so that results are redoable. If an app NEEDS to be delete it should be done by UCloud dev in that case but any apps that does not work should never leave dev.
