### ISSUE TITLE
Change look of App store tools

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#1968]
Replace tool list with collection of tools similar to how applications are shown.

Possibilites:
    - Cards similar to apps
    - More square-ish cards for each tool.

Clicking should in either case lead to the "Show All" page for the tool.

**Comment by DanThrane** [comment]
Putting this on hold until we have a concrete design.

**Comment by DanThrane** [comment]
Handled by epic in P5.
