### ISSUE TITLE
Reset password functionallity

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#1988]
We need a way to reset peoples password when they are username/password users. As of now the easiest way for us is to create a new user with the password and then manual copy the new password to the old user in the DB and then delete the new user along with storage clean up.

Ideally this would be an automatic process where
- the user request a reset from our login page using their email
- we send an email containing a one time usage link to a reset page
- the user resets the password and is forwarded to UCloud login page

We do however not expect to have many username/password users because most of the people should be using a WAYF/EDU login and  their credentials is from a third party. Therefore a form on the ADMIN page could suffice - enter username and email and their new password (twice). People will contact us by email and we do the change. An email is automatically send from the backend to the user containing their new password.

Option 1 is the most ideal, but will also be more time consuming in implementation 
Option 2 is quite trivial to implement, but if this becomes a larger problem due to EDU gain not being able to function, then the amount of username/password users will be to large and we risk to do a large number of reset manual.

**Comment by DanThrane** [comment]
The password reset service you are describing already exists. I think we may have disabled it do to lack of email support (until now)
