### ISSUE TITLE
[scheduling] UI for managing components

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#1996]
We will be introducing various new 'components' which like compute jobs and files are resources in UCloud but they don't really make sense on their own. Rather they always need to be connected to one of our primary resources (jobs/files). These include:

- (Floating) IP addresses
- Disks (Block devices)

**Comment by Tiggles** [comment]
This issue is outdated, right? @DanThrane

**Comment by DanThrane** [comment]
Yes
