### ISSUE TITLE
Integrate Support tickets with JIRA

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#1999]
Currently we only recieve support tickets in slack. We need to integrate this with our JIRA platform.
A perfect solution would be an in-platform solution where we integrate JIRA directly into our support field. 

For now we might just be able to send an email from the backend to our support mailbox with the original sender as email sender. Since JIRA already polls from support@escience.sdu.dk this should fix the problem. 

Bug reports should still only send to slack, or be integrated with github (What do you think @DanThrane ).

(Issue number https://www.youtube.com/watch?v=weUhBGA8mxo )

**Comment by DanThrane** [comment]
> Bug reports should still only send to slack, or be integrated with github (What do you think @DanThrane ).

Lets send them all to JIRA. If the issue they are describing turns out to be a bug we can create an issue manually in the github repo.
