### ISSUE TITLE
Rework the app-search functionallity

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2001]
The app voilà cannot be found when searching.
It exists in both postgres and ES, but their titles are different. ES: voilã Postgres:voilà
This might happen during creation.

Voilà - Can be found when adding the field "name" to the elasticsearch searchquery and searches voila due to the name being without accent.

**Comment by Tiggles** [comment]
Any reason why `v`, `vo`, `voi` or `voil` doesn't return the application?

**Comment by hschu12** [comment]
No - I am not sure if it is elastic that does not finds it or if it is filtered out when we search the DB because elastic returns a "wrong" title. Have to check the query in debug mode and see what it returns.

**Comment by hschu12** [comment]
When deleting the app and reuploading it there was not an issue, making it hard to reproduce. The reload (done twice) shows no difference in spelling or letters posgres and elastic and the app was searchable without any problems. v, vo, voi, oi etc all works when attempting to find the app now.

**Comment by hschu12** [comment]
Problem has returned
