### ISSUE TITLE
Enhance resource information (Credits)

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2003]
Credits remaining (both on dashboard, app run and other places) does not subtract the reserved amount.

I suggest that we either have the same layout as now and simply subtract the reserved credits from the total.
Otherwise we do as with quota and write credits/reserved for jobs  1000/799 or something like it.

We do check on the backend if there is enough resources when starting a job but from the info on the screen one should have enough credits.

![Screenshot 2020-11-19 at 14.24.28.png](https://images.zenhubusercontent.com/5e2056498804633f5bf42bf3/162cec85-b491-4edf-a56a-eb7652d529bf)

**Comment by hschu12** [comment]
Perhaps consider showing message when adding job that makes you go close to 0.

**Comment by DanThrane** [comment]
No longer an issue after `scheduling` is merged
