### ISSUE TITLE
[storage] Browse files for upload does not work in Safari

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2007]
When attempting to click browse to select files for upload nothing happens.
Reproducable on MacOS 10.14.6 with safari 14.0.1 (14610.2.11.51.10)

**Comment by Tiggles** [comment]
Can't reproduce on MacOS 11.2, Safari 14.0.3

**Comment by Tiggles** [comment]
Still works for me. Closing for now.
