### ISSUE TITLE
Required information to permissions for apps and license unclear

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2016]
It is unclear that it is the entire project "location" that has to be given. Not only the project title.

What information is required: "SDU/SDU-NAT/Project Titel"

<img width="1006" alt="Screenshot 2020-12-01 at 11 40 08" src="https://user-images.githubusercontent.com/10943804/100730231-1a256200-33ca-11eb-91b9-ecd0f1005526.png">

**Comment by Tiggles** [comment]
Maybe a dropdown would be preferable? Unless this also refers to projects that you aren't a part of?

**Comment by hschu12** [comment]
I think a dropdown would be to extensive. To set permissions for licenses and apps is a UCloud-admin feature, which means if we show a dropdown of projects this would have to show all projects.

We could of course integrate this more with the project feature and have an index in Elastic with all project titles or even more metadata (Could perhaps just use Postgres if possible) to do search by typing as we do with the contactbook feature except that the title is searchable after project creation and not after first usage which is the case with shares in contactbook.

**Comment by Tiggles** [comment]
Maybe something like the file-selector, but for projects?

**Comment by Tiggles** [comment]
Fixed on branch 'transferApplicationIssue'
