### ISSUE TITLE
Email notification on Application 

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2049]
When approving we should not send out following message to the approvers (PIs and Admins of recieving project):

>Dear HenrikSchulz#6398
>
>We are glad to inform you that your application for resources from SDU-NAT has been approved.
>
>If you do not want to receive these email notifications, you can unsubscribe to non-critical emails in your personal settings on UCloud
>
>Best regards,
>
>The UCloud Team
>SDU eScience Center

It does make sense. We could still send an email so the admins now that there have been approved a project, but as it is now it seems as they had an application themselves.
Solution: Change text or do not send to approving part. Would prefer change of text.

**Comment by Tiggles** [comment]
Maybe change 'We are glad to inform you' to 'We are happy to inform you'
