### ISSUE TITLE
Improvements to Grafana Dashboard

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2063]
List of potential improvements (to be clarified later before we put this on the roadmap):

- Fix data loading issues
- Clean up/combine some of the data
- Improve response times, potentially, using caching of responses

**Comment by hschu12** [comment]
Cleaned up and added additional information for signed up users (Daily change and total number of users per day) as well as an alert at 1000 users.
@DanThrane  @claudiopica Will you checkout the dashboard and tell me if you find it adequate or if there is something missing.
