### ISSUE TITLE
[scheduling] Remove automatic retries from backend and frontend

### ISSUE THREAD

**Issue by xiroV** [SDU-eScience/UCloud#2089]
Original issue below.

Automatic retries were once needed due to other issues in our infrastructure. These issues are no longer present and we are paying the price in the form of duplicate entries because of retries. Typically caused by timeouts.

----

Upon starting an application, multiple jobs are (sometimes) created. The bug was discovered locally and I was able to reproduce it multiple times on production using the CentOS XFCE and Coder C++ applications.

![image](https://user-images.githubusercontent.com/911284/104316561-f2eba580-54dc-11eb-97b5-af4cbe72de5f.png)

**Comment by Tiggles** [comment]
Possibly fixed on scheduling. It makes sense that we try to recreate it there as well.

**Comment by xiroV** [comment]
@Tiggles I'm currently running a subbranch of scheduling locally, meaning that the bug likely persists on the scheduling branch as well.

**Comment by Tiggles** [comment]
If you are trying to reproduce this, could you check the response when submitting a job? Sometimes, the return code is 5xx, but it is still started, which could be why it submits multiple jobs.

I'm guessing this is not an issue if you name your job.

**Comment by xiroV** [comment]
@Tiggles I was thinking something along those lines as well. Since the backend has changed a lot between master and scheduling, this could be a frontend issue, but I haven't investigated it any further yet.
