### ISSUE TITLE
Stray rename field for resource allocation

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2132]
![image.png](https://images.zenhubusercontent.com/5e188a7332969d45e20e5d13/c5431ac8-bb15-413e-857b-2bc0116c4aea)

Observed by Claudio. I have been unable to reproduce this issue locally.

**Comment by hschu12** [comment]
Unable to reproduce. It is not even possibble to rename projects from this page.
Closing for now.

**Comment by DanThrane** [comment]
See slack message.
