### ISSUE TITLE
[scheduling] Animation loading issue for Jobs/View

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2140]
Steps to reproduce:

- Just load a bunch of times and it should get stuck

**Comment by xiroV** [comment]
I'm pretty sure I've experienced this, but thought it was related to my machine being overburdened. I experienced it when I was running low on RAM and all my CPUs was in use. Could it be something as simple as that?

Currently I'm not able to reproduce, after refreshing the page of a single-node and multi-node job ~20 times each, in both Firefox and Chrome.

**Comment by DanThrane** [comment]
Stale issue, has not observed in a long time.
