### ISSUE TITLE
Attempt to make mapping for indices (ES)

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2153]
When reindexing we are experiencing problems with the dynamic mapping which is based on the first couple of indices moved. Making a specific mapping for these indices should remove the issue.

Problem with mapping seen with: 

http_logs_app.compute.kubernetes.cancel
http_logs_app.compute.kubernetes.cleanup
http_logs_app.compute.kubernetes.followwsstream
http_logs_app.compute.kubernetes.jobprepared
http_logs_app.compute.kubernetes.jobverified
http_logs_app.compute.kubernetes.queryinternalwebparameters
http_logs_hpc.tools.findbynameandversion

The kubernetes indices is mostly because of different structures of each app and the mapping should perhaps just take it as an object instead of trying to dynamically map the job object

**Comment by DanThrane** [comment]
Stale issue.
