### ISSUE TITLE
Add more information to job when we kill jobs due to maintainence

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2158]
We could increase the amout of information in job results:

From Sofie Marie Koksbang after we killed her jobs on the 2/2:
"I think it would be a good idea to perhaps give a little more information on the page that pops up when one clicks on the failed job so that one gets to know when the job was killed, that it was necessary and one can read more on the "front page" and that the run will be free of charge."

**Comment by emolinaro** [comment]
I agree, the more information we add the better it is.

**Comment by DanThrane** [comment]
This should be doable by modifying the API used for maintenance in the upcoming release, currently on `scheduling`.

**Comment by DanThrane** [comment]
As of 2021.3.0 this depends on the provider. I believe we have this information already.
