### ISSUE TITLE
Limitations to number of emails to each application?

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2174]
I could perhaps be interesting to look into the posibility to reduce the number of emails send.

Example: 
If a user has recieved a comment on an application and then recieves one more before (s)he had time to check the earlier comment, should we send a new mail or could we implement a solution so that unless he have read the comment then he would not need to have a new mail. He/she already knows that a comment is awaiting him/her.

This issue is not needed in order to close the epic, but should be investigated.

**Comment by xiroV** [comment]
So the user would only receive one email, regardless of the number of comments, given that the user have not read any of the comments yet?

Tbh. I think this behaviour could end up being a bit confusing. Also, I'm guessing it could become complicated to keep track of which comments are "read" and not.

Personally I think it would be better just to have a "mute" button or similar, to prevent getting email notifications on comments for that applications.

Or perhaps a middle-ground solution could be that the user can opt-in to only receive a daily "summary" mail containing the number of new comments on the application.

**Comment by hschu12** [comment]
We will see how the mail update works with greater granularity before implementing somthing like this or daily summary emails. Closing issue
