### ISSUE TITLE
[storage] Clearify importance of folders in project root folder (ACL base check)

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2175]
Folders in root of projects are the base for our Group and ACL check for files in projects.
However I seems that we might not be clear enough on that these are folders but not meant to be moved (which is disabled). 

We could perhaps change the icon from folder to something else that does not give the impression that these are folders as every other but more an entry point?

https://jira.cloud.sdu.dk/browse/TICKET-174  (Unable to move folders in a project)

**Comment by DanThrane** [comment]
I think we should try to combine this with the `file-orchestrator` rework. I'll add this issue later when I create the epic. I am still working on the final pieces of the design.

**Comment by DanThrane** [comment]
Resolved by using different terms and icons in the frontend.
