### ISSUE TITLE
[scheduling] Missing error handling on the frontend

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2198]
![image.png](https://images.zenhubusercontent.com/5e188a7332969d45e20e5d13/d5c05cd6-83d6-4748-8d5a-d086f046b923)

I am unsure which error the frontend received, but it wasn't handled correctly. By default this should probably show some kind of generic error message instead of showing an empty box. Whoever works on this issue could also investigate if we are sending any known error code/messages that the frontend isn't handling.

**Comment by Tiggles** [comment]
Any idea how this was triggered?

**Comment by DanThrane** [comment]
All I know is that Emiliano submitted a job with settings as shown in the screenshot. It did not trigger after resubmitting the application.

**Comment by Tiggles** [comment]
It works for me, both in Personal Workspace and in a project. I happened for Emiliano using a project. I'll try to see what happens if I don't have enough resources.

**Comment by Tiggles** [comment]
Not having enough compute resources correctly complains about that. Not having storage correctly complains about that. And from the image we can see compute credits is not the issue.
