### ISSUE TITLE
Visual datepicker bugs on Runs page

### ISSUE THREAD

**Issue by xiroV** [SDU-eScience/UCloud#2221]
The datepicker used in the Quick Filters section on the Runs page works as intended, but there seems to be several visual bugs.

1. ~~The width of the datepicker expands beyong the width of the sidebar, causing a horizontal scrollbar to appear in the sidebar.~~ (fixed in fd7550aff4192b866f80a1044b015ba0272115a1)
2. Hovering a date in the calendar shows the `not-allowed` cursor, even though you can still select the date,
3. (Matter of personal preference) the calendar is set to start each week on a Sunday.

**Comment by Tiggles** [comment]
We are behind on the updating of the npm package, but it doesn't support React 17 yet

https://github.com/Hacker0x01/react-datepicker/pull/2700
