### ISSUE TITLE
Proposal for new Filters UI

### ISSUE THREAD

**Issue by xiroV** [SDU-eScience/UCloud#2223]
On the Runs and Activity page we have the Filters UI in the sidebar. It takes up a lot of space, and it isn't always completely obvious which filter has been selected. As an example, pressing the quick filter "Today" does not highlight "Today", but adds dates to the "Active filters section", which might not be apparent.

I would like to propose that we redesign this to something that takes up less space (at least when not in use), and at the same time makes it more apparent which filters are active.

An example draft could be something like the following:

![image](https://user-images.githubusercontent.com/911284/107747771-48071b00-6d18-11eb-81ff-5ee002d6f1e8.png)

The downside to this is that the user would need at least 2 clicks to apply a filter instead of 1.

**Comment by DanThrane** [comment]
Fixed as part of #2395
