### ISSUE TITLE
[scheduling] Implement a max size for app store cards

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2237]
See image below. Let's implement a max width for these card so they don't span across large wide-screen monitors.

![image](https://user-images.githubusercontent.com/1782437/108332625-4b931a00-71d0-11eb-8ca4-0765c16e1d04.png)

**Comment by Tiggles** [comment]
Would it make sense to change the `transform: scale(1.02)` to something more fixed while we're changing the width? It's exceeding the containers in a lot of cases.

**Comment by xiroV** [comment]
Personally I still don't like the scale effect. Also, it makes the text in the elements render weird when hovering in Firefox.

**Comment by Tiggles** [comment]
I think it needs to be there, but I have the same issues.

**Comment by DanThrane** [comment]
If it helps you can tweak the scale a bit but I think we should keep the effect for now.

**Comment by Tiggles** [comment]
I'm thinking something more along the lines of `:hover { height: calc(100% + 3px); width: calc(100% + 5px);}` instead of scaling relative to its own size. That seems to create small or big differences in some cases.

**Comment by claudiopica** [comment]
@Tiggles I don't this a viable solution: it will change the aspect ratio. animating/changing height and width will also trigger layout.
