### ISSUE TITLE
Some old JobParameters are unable to load

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2246]
Example:

```
{"siteVersion":1,"application":{"name":"coder","version":"1.939-R2"},"parameters":{},"numberOfNodes":1,"maxTime":{"hours":1,"minutes":0,"seconds":0},"mountedFolders":[]}
```

**Comment by Tiggles** [comment]
What is failing to load? Everything?

**Comment by Tiggles** [comment]
One failure when importing parameters from older versions,

another failure is when importing parameters from different app

**Comment by Tiggles** [comment]
Some optional parameters are randomly selected as in use on import.
