### ISSUE TITLE
JobView doesn't always transition correctly on cancel

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#2250]

**Comment by Tiggles** [comment]
Reported by @claudiopica. Can't reproduce easily on either Chrome or Firefox.

**Comment by Tiggles** [comment]
Tried FireFox and Chrome, no cases. Tried with My Workspace and a project, still no cases.

**Comment by Tiggles** [comment]
Firefox only updates the animations when the tab is in focus. Chrome doesn't care if the tab is in focus. Figured it would be the other way around.

**Comment by DanThrane** [comment]
I think this is most likely related to websocket connection not being kept alive (correctly). This bug was also present on the old version.

**Comment by Tiggles** [comment]
So is this a frontend or a backend issue?

**Comment by DanThrane** [comment]
Frontend

**Comment by DanThrane** [comment]
I now suspect this might be caused by a response being sent before the final state update is sent.

**Comment by Tiggles** [comment]
Would that result in `newState` being `null`?

**Comment by Tiggles** [comment]
Did it use to be easier, or was it always difficult to reproduce for you?

**Comment by claudiopica** [comment]
@Tiggles yes before was very easy to reproduce. so the situation has certainly improved.
