### ISSUE TITLE
Add search criteria fields for files search in main view

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2257]
We have moved the search criterias for the app search to the main container. We should do the same for files:
![Screenshot 2021-02-25 at 08.40.04.png](https://images.zenhubusercontent.com/5e2056498804633f5bf42bf3/f4063469-ecf6-41b2-8016-b6c3e0ff0853)

**Comment by claudiopica** [comment]
@hschu12 I am not sure why this was moved, but I don't think it looks good now. Any reasons not to leave it in the search box?

**Comment by hschu12** [comment]
not that I know of. @DanThrane ?

**Comment by DanThrane** [comment]
Probably not a good one, but you'll have to look into the code to see if I had a good reason. I think I simply didn't get around to fixing this.

**Comment by Tiggles** [comment]
I can't find any reason for having a different behaviour compared to File Search.

**Comment by Tiggles** [comment]
I have hidden the Application Search widget on larger screens, using the same approach as for File Search
