### ISSUE TITLE
[storage] Separate Download and zipping

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2278]
Users should not be allowed to download folders anymore but be able to zip them
Marking multiple files/folders should allow for zipping

Only files should be downloadable

**Comment by hschu12** [comment]
Created possible solution in https://github.com/SDU-eScience/UCloud-Apps/issues/750

**Comment by DanThrane** [comment]
In 2021.3.0 we will be doing this through applications (see Henrik's comment).
