### ISSUE TITLE
Incorrect time in "Used" card in Job View UI

### ISSUE THREAD

**Issue by xiroV** [SDU-eScience/UCloud#2281]
The "Used" card in the Job View page seem to show the total time allocated for the job.

However, if a job expires (for example because of insufficient funds), that time is incorrect. I think this card should show how much time was actually used, not how much time was allocated.

I assume the `last_update` timestamp could be used to calculate this, but I'm not sure.

**Comment by Tiggles** [comment]
How can you run out of funds? Expanding the job beyond the initial job submission?

**Comment by Tiggles** [comment]
Yes.

**Comment by Tiggles** [comment]
Jobs that terminate due to missing funds does not contain a state that shows this, so it is not viable.
