### ISSUE TITLE
Tooltip is not working correctly (at least for project roles)

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2283]
![image](https://user-images.githubusercontent.com/1782437/109963677-fcc7a300-7cec-11eb-9528-7a419bd57350.png)

**Comment by claudiopica** [comment]
Sensitivity of files in file table has the same problem.

**Comment by Tiggles** [comment]
The tooltip file hasn't been touched in 13 months. This is weird.

**Comment by Tiggles** [comment]
The Box had `top` props added that messed with other components. Has been moved to child `components` that require the styling.
