### ISSUE TITLE
Infinite loop in indexing

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2296]
It looks like we might accidentally have code which is following symbolic links which the indexing code is not supposed to do.

**Comment by DanThrane** [comment]
I have confirmed that this is indeed an issue. It looks like we are no longer checking if the file is a symbolic link in the `submitScan` function. We should just filter out all files which are symbolic links.

**Comment by Tiggles** [comment]
Fixed in 113a7e3b444f9f8c5dc322588e9cac7aad559ac6 on [scheduling-fixes]
