### ISSUE TITLE
[scheduling] Cancelling a job immediately can cause it to stay stuck in IN_QUEUE state

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2326]
This was observed in an integration test which immediately called cancel after calling create. This bug is specific to app-kubernetes (UCloud/compute)

**Comment by xiroV** [comment]
Attempted to reproduce using a script which starts a job followed by an immediate cancel request of the same job, repeated 20 times. All jobs stopped correctly in the success-state.
