### ISSUE TITLE
Trim input fields

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#2331]
Trimming input fields would, among other things, affect password and username fields.

While the usernames don't contain leading or trailing spaces, passwords are allowed to contain leading and trailing slashes, and would be less secure as a result.

We don't have that many password users, so this likely won't affect that many users.

We are an open-source project intended for other people to download and run, so if this change is made, this needs to be communicated clearly. One solutions is a warning when the input field is of type 'password' contains a trailing or leading whitespace. But this kind of goes against the point of hiding the content in the input field in the first place.

What else could this affect?

**Comment by DanThrane** [comment]
Stale issue.
