### ISSUE TITLE
Jobs started with quick launch have invalid JobParameters.json file

### ISSUE THREAD

**Issue by claudiopica** [SDU-eScience/UCloud#2339]
In particular `"timeAllocation":null` (while jobs are started for 1 hour).
I am not sure the format per se is invalid, but 
1) it does not correspond to the job launched
2) it is not possible to restart thr job using the provided JobParameter file

**Comment by claudiopica** [comment]
An example of parameter file created: 

> {"siteVersion":2,"request":{"application":{"name":"terminal-ubuntu","version":"0.16.0"},"product":{"id":"u1-standard-1","category":"u1-standard","provider":"ucloud"},"name":null,"replicas":1,"allowDuplicateJob":true,"parameters":{},"resources":[{"type":"file","path":"/home/ClaudioPica#7566/Jobs/Terminal Ubuntu/d9950f7b","readOnly":false}],"timeAllocation":null,"resolvedProduct":null,"resolvedApplication":null,"resolvedSupport":null},"machineType":{"cpu":1,"memoryInGigs":6}}

**Comment by xiroV** [comment]
Fixed in #2359
