### ISSUE TITLE
[resources] Any resource page can show duplicate entries

### ISSUE THREAD

**Issue by claudiopica** [SDU-eScience/UCloud#2340]
On reload the page is correct. I am not sure this is source of the problem but this seems to happen when a workspace only has 1 run. 

<img width="948" alt="Screenshot 2021-03-29 at 18 14 02" src="https://user-images.githubusercontent.com/1016452/112867064-c5190480-90ba-11eb-9966-d886626a0cc1.png">

**Comment by DanThrane** [comment]
I wouldn't rule out that this could be a backend issue that is specific to if only one entry is returned. @Tiggles Can you confirm if this is a frontend/backend bug?

**Comment by Tiggles** [comment]
I'll give it a look.

**Comment by Tiggles** [comment]
I'm having issues recreating this. Created a subproject and ran one job. I can't see more than one job here.

@claudiopica How are you experiencing this? Personal Workspace? Project? Is this an old job?

**Comment by DanThrane** [comment]
I have confirmed that this is a general issue and I was able to reproduce it for the resources epic by repeatedly reloading the page.

**Comment by Tiggles** [comment]
Can't reproduce it by reloading page, but changing from project to another project while on the Runs page reproduces it for me.

**Comment by Tiggles** [comment]
Browse is called twice. This might be why the merging of the pages happens twice.
<img width="718" alt="Screenshot 2021-06-18 at 12 26 28" src="https://user-images.githubusercontent.com/7610257/122547489-74b5a100-d030-11eb-8d6b-707b85e53afc.png">
