### ISSUE TITLE
[UCloud/Compute] Input file command invocation breaks some apps

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2341]
> When I run LAMMPS I need to put a directory which contains all the necessary files, and the input file (which is causing from few days the problem I wrote to you, namely when I submit the jobs he gave me as error

```
Cannot open input script /work/brownian.lam/ (../lammps.cpp:440)
```

> and I notice he put a / after the name of the file. I noticed this because also in another app I am implementing he complain:

```
NotADirectoryError: [Errno 20] Not a directory: '/work/metadata.json/'
```

> in the yml file I use a `input_file` type

Report by Federica.

It would appear that this is a breaking change in how we used to pass the `input_file` as a command invocation. We probably used to perform a check on the file to determine if we needed to add a trailing slash. I believe this check is now gone. We should fix this issue by re-implementing the old approach.

**Comment by emolinaro** [comment]
This issue affects the correct functionality of most of the apps.
