### ISSUE TITLE
Search button for advanced filesearch does not respond

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2356]
No request is sent on click.
Still works with enter from the searchbar text field.

**Comment by Tiggles** [comment]
Have you tried changing the search string?

**Comment by hschu12** [comment]
Yes - seems to be working on inital search but not on following

**Comment by Tiggles** [comment]
I think that's intended behaviour. If the search string isn't changed, the simple-search call won't result in anything different. So I think an equality check needs to be removed.

**Comment by DanThrane** [comment]
Handled by storage epic.
