### ISSUE TITLE
Ktor occassionally fails with ResponseAlreadySentException

### ISSUE THREAD

**Issue by xiroV** [SDU-eScience/UCloud#2372]
During the weekend (April 16-18) this error occurred multiple times.

According to a [old ktor issue](https://github.com/ktorio/ktor/issues/142) this could be caused by a broken pipe:

> ... while sending a response an exception (IOException: Broken Pipe) occurred because client closed connection. Instead of cancelling pipeline in a proper way we assume that there is a problem in the code and try to respond with (500 Internal Server Error), and this fails again, because headers has already been sent.

I'm unsure if it's the same problem we have, and whether the above issue have already been fixed in ktor.

Seems to happen when responding from `/ucloud/ucloud/jobs/app-authorization/`.

**Comment by DanThrane** [comment]
Stale issue.
