### ISSUE TITLE
App-kubernetes loses track of jobs/connection to Kubernetes

### ISSUE THREAD

**Issue by xiroV** [SDU-eScience/UCloud#2373]
During the weekend (April 16-18), we had several cases where app-kubernetes responded with:

```
cloud.app.kubernetes.services.JobManagement - We appear to have lost the following job: ...
```

In the same time frame, it seemed like we had problems with the connection to kubernetes, which could be causing the above.

```
WARNING cloud.app.kubernetes.services.JobManagement - An exception occurred while processing Kubernetes events
```

We should investigate why we occasionally lose connection to kubernetes though.

**Comment by DanThrane** [comment]
Assumed to no longer be true for 2021.3.0
