### ISSUE TITLE
Misinfomation about access to folders from runspage

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2381]
If an admin goes to a job run by a normal user, then folders mounted by the user will have the flag "Usable only by admins" next to it even though this is a folder that the users group has access to.
I think this is because we do not get groups on the run page and it is an admin showing a folder located in a project "without" a group attached.

Think this a frontend only thing

Badly explained - contact @hschu12 for a perhaps better explaination

![Screenshot 2021-04-21 at 16.32.10.png](https://images.zenhubusercontent.com/5e2056498804633f5bf42bf3/9a13c80a-36f9-4c3a-a111-05bda66dec10)

**Comment by DanThrane** [comment]
This is just a frontend issue. I believe it has already been fixed in the file orchestrator epic.

**Comment by Tiggles** [comment]
Should this be closed?

**Comment by DanThrane** [comment]
No longer relevant as of 2021.3.0.
