### ISSUE TITLE
Improved feedback on queue state 

### ISSUE THREAD

**Issue by claudiopica** [SDU-eScience/UCloud#2386]
Some jobs cannot be scheduled because there is no available machine of the selected type.
Currently we only show the users two messages: "UCloud has accepted your job into the queue" and "We are currently preparing your job. This step might take a few minutes.". 
The second one is quite misleading as this might take a very long time.
We have a special message in case the overall cluster utilization is very high, but that does not help much (e.g. it is useless for GPU jobs).

We should be able to show a different message to the users where the machine type requested is not available, and inform that this can take a long time.

**Comment by DanThrane** [comment]
Handled by #2425
