### ISSUE TITLE
Zip folder download un-extractable archive

### ISSUE THREAD

**Issue by KapitanKabzon** [SDU-eScience/UCloud#2387]
Windows 10 2004,
7-Zip 21.01 .
When downloading a folder from UCloud, the resulting *.zip file has weight, but when opened with 7-zip or native windows it cannot be extracted due to error. [LINK](https://i.gyazo.com/ece4a75bc9c22ecba37b8aac9a23bfe0.png) .
The zip: [LINK](https://github.com/KapitanKabzon/EiT_Metal/raw/master/Checkpoints.zip)

**Comment by hschu12** [comment]
Possible solution: https://github.com/SDU-eScience/UCloud-Apps/issues/750
