### ISSUE TITLE
Improve report of usage for jobs 

### ISSUE THREAD

**Issue by claudiopica** [SDU-eScience/UCloud#2389]
This is an example output from a 128 node job, each node is 2 cores, walltime used ~4 minutes.

<img width="817" alt="Screenshot 2021-04-27 at 18 55 19" src="https://user-images.githubusercontent.com/1016452/116281727-49c67380-a78a-11eb-856d-7018fa559746.png">

What we report is the "machine-type time" which makes good sense since this corresponds to the price.
However it might not be clear the user.
I think we should at least add another information, which is the "walltime" used (the one we reported divided by the number of nodes).

In addition one might consider also adding the core*hours time (i.e. the one we report times the number of cores for the machine-type). In this case for GPU nodes, we should also report the GPU*hours.

**Comment by hschu12** [comment]
#2382
