### ISSUE TITLE
Send email when switching to Running State of job

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2408]
Remember to add checkbox to email settings

**Comment by hschu12** [comment]
Maybe add to Succes and Failure as well.

**Comment by claudiopica** [comment]
@hschu12 this should only be sent if the job has been in the queue more that X minutes, where we can set X (not user preference). X can be e.g. 60min, i.e. one hour for now.

**Comment by DanThrane** [comment]
Stale issue. I think we should revisit this later. We will probably want to consider how providers change this isse.
