### ISSUE TITLE
grant application panel not working

### ISSUE THREAD

**Issue by claudiopica** [SDU-eScience/UCloud#2438]
the number of application in progress is not updated correctly.

<img width="351" alt="Screenshot 2021-05-26 at 18 11 40" src="https://user-images.githubusercontent.com/1016452/119694912-f9f0d000-be4d-11eb-84e0-0319405d36c8.png">

**Comment by Tiggles** [comment]
Caused by bad request.

**Comment by Tiggles** [comment]
Result of a bad request. The "filter" parameter was missing due to of typings use.
