### ISSUE TITLE
[reporting][P5/M3] Overview of HPC services/reporting

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2450]
Design of UX and UI for: 

 1. overview of resources available at DeiC HPC centers; 
 2. current utilization of DeiC HPC centers. 

The functionality is described below in WP1.

**Comment by claudiopica** [comment]
@Tiggles we will also need a kind of overview which is similar to the "resources" page in a project

**Comment by Tiggles** [comment]
Correct. The images are only for the first point. I'm not sure how easy point 2 is currently, either for our own system or another site's system.
