### ISSUE TITLE
[storage] Uploads do not automatically resume

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2546]
I suspect this might be a result of a merge conflict gone wrong. The code was working before merging the latest PR.

**Comment by Tiggles** [comment]
Adding 6 files one by one seems to work correctly, with the 6th starting after one of the initial 6 finishes. Codebase at time of writing was equal to the `storage` branch.

**Comment by xiroV** [comment]
Not sure if this was the issue, but there's still something strange with uploads.

 1. After selecting a file it is uploaded correctly, but there's no indication that the file was uploaded (except for it being present in the file list of the modal),
 2. when closing the upload modal, the new files are not shown in the file browser before refreshing.
