### ISSUE TITLE
Provider metadata

### ISSUE THREAD

**Issue by romh87** [SDU-eScience/UCloud#2593]
Currently the job request contains a json with provider productId, cpu, mem, gpu
We need to include this information in the provider meta, and populate slurm job parameters based on local provider information for that specific product id.

The UCloud interface will populate the available products based on this information at the time the provider is added.

```
{
    "compute": {
        "products": [
            { "category": "im1", 
              "id": "im1", 
              "ppm": "1.1", 
              "description": "My product description", 
              "cpu": "100", 
              "mem": "1", 
               "gpu": "0"
            }
        ],
        "plugins": [
            {"id": "sample"}
        ]
    },
    "connection": {
        "ticket": {}
    },
    "identityMapper": {
        "direct": {}
    }
}
```

**Comment by romh87** [comment]
Also here the unit conversion must be addressed. For SLURM we can only allocate physical cores and memory in MB.

**Comment by DanThrane** [comment]
This is no longer required.
