### ISSUE TITLE
Removal of permissions for one group, sometimes removes for others

### ISSUE THREAD

**Issue by xiroV** [SDU-eScience/UCloud#2607]
In project files, if permission/access rights are removed (set to `None`) on a folder for one group, then permission is reset for all groups on that folder (as far as I can tell).

Reproduction:
 - Create 2 groups in a project,
 - Create a folder in project Files,
 - Set permission for both groups to `Read`, and press update.
 - Set permission for one of the groups to `None`, and press update.
 - Press Cancel, and open the Permissions modal again.
 - If everything looks correct, try setting the permission of one of the groups back to `Read`, press Update -> Cancel and open the permission modal again.

**Comment by Tiggles** [comment]
Fixed in #2604 2605
