### ISSUE TITLE
[im] Life-cycle handling of Slurm jobs

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2612]
This issue tracks handling the typical life-cycle events of a Slurm job. The
life-cycle events of a Slurm job matches roughly one-to-one with the life-cycle
events of a UCloud compute job. The following table attempts to map the states
of a Slurm job to a UCloud job:

| Short code | Long code         | UCloud State | Notes                       |
|------------|-------------------|--------------|-----------------------------|
| `PD`       | `PENDING`         | `IN_QUEUE`   |                             |
| `R`        | `RUNNING`         | `RUNNING`    |                             |
| `S`        | `SUSPENDED`       | `IN_QUEUE`   |                             |
| `CG`       | `COMPLETETING`    | `RUNNING`    |                             |
| `CD`       | `COMPLETED`       | `SUCCESS`    |                             |
| `BF`       | `BOOT_FAIL`       | `FAILURE`    |                             |
| `CA`       | `CANCELLED`       | `SUCCESS`    |                             |
| `CF`       | `CONFIGURING`     | `IN_QUEUE`   |                             |
| `DL`       | `DEADLINE`        | `EXPIRED`    |                             |
| `F`        | `FAILED`          | `SUCCESS`    | See note 1                  |
| `NF`       | `NODE_FAIL`       | `FAILURE`    |                             |
| `OOM`      | `OUT_OF_MEMORY`   | `SUCCESS`    | Explain OOM in status       |
| `PR`       | `PREEMPTED`       | `FAILURE`    | Explain in status           |
| `RD`       | `RESV_DEL_HOLD`   | `IN_QUEUE`   |                             |
| `RF`       | `REQUEUE_FED`     | `IN_QUEUE`   |                             |
| `RH`       | `REQUEUE_HOLD`    | `IN_QUEUE`   | Explain in status           |
| `RQ`       | `REQUEUED`        | `IN_QUEUE`   | Explain in status           |
| `RS`       | `RESIZING`        | `IN_QUEUE`   | Explain in status           |
| `RV`       | `REVOKED`         | `FAILURE`    | Explain in status           |
| `SI`       | `SIGNALING`       | `RUNNING`    |                             |
| `SE`       | `SPECIAL_EXIT`    | `RUNNING`    |                             |
| `SO`       | `STAGE_OUT`       | `RUNNING`    |                             |
| `ST`       | `STOPPED`         | `RUNNING`    | Explain in status           |
| `TO`       | `TIMEOUT`         | `EXPIRED`    |                             |

Note 1: UCloud jobs only enter `FAILED` if it failed because of the provider,
in this case Slurm's failed state is referring to the user's own software
exiting with a non-zero exit code. We do not consider this a failure of the
provider. Even if this is, somehow, caused by the provider, it is hard to
differentiate between actual provider errors and user jobs simply failing.

The integration module can provide an update through the control interface.
This allows them to set both a new state and a status message. The status
message should be used to explain certain events, as described in the notes.
For example, this can be useful to explain that a job was terminated because
it ran out of memory.

This should be implemented by running a monitoring loop in the server instance
of the UCloud integration module. This could run a command, such as `squeue` to
retrieve the relevant information. For this initial version, we will assume
that the Slurm cluster is configured to allow any user to view the state of
another user's job. This is a very common configuration and should be
sufficient for this version.

**Comment by romh87** [comment]
https://docs.google.com/document/d/1nDY2NRsIYMlZXJWxywy5Gtfisq1h4a94hme3QKjHk-g/edit?usp=sharing
