### ISSUE TITLE
[storage] File favorite deletion sometimes uses an empty string in the request

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2687]
I'm guessing that this is related to improper use of state or potentially a lack of refresh.

**Comment by DanThrane** [comment]
Issue is still present and appears to be related to the `setState` call.

**Comment by Tiggles** [comment]
As far as I can tell, the file must never have been a favorite file.

**Comment by Tiggles** [comment]
Blocked by #2693
