### ISSUE TITLE
WAYF login from the Safri browser fails and redirects to login page

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2700]
When using UCloud with the safari browser you are not able to login using WAYF.
You are correctly redirected to the login page of the institution but on the redirect back to UCloud it seems to be missing some sort of authentication token/header. This results in a redirect back to the login page. Further attempts remebers that you have logged into the institution and simply redirects back to login page again and again.

This issue is browser specific and might even be WAYF who sends the wrong information back to us, so it can be hard to fix on our side.

**Comment by Tiggles** [comment]
Can't reproduce on MacOS Safari or iOS Safari.
