### ISSUE TITLE
Accidentally going to previous page when using FileSelector in job creation 

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2747]
Request from Erik.

When selecting a file for a job, one might accidentally use the "swipe back" motion on touchpad or previous page button on mouse when attempting to go to previous folder. 
This results in leaving the app page and loosing all progress of job setup.

Example:
- I am trying to setup a job. 
- I have to select an input folder and the file selector dialog opens. 
- I go into the wrong folder
- I want to go to the the parent folder again
- I accidentially use the back button/swipe back motion
- I go back to previous page and have lost all setup of job. 

Can this be avoided? (E.g blocking page back when a pop op is active)
Or even better can we make the swipe/back button trigger the ".." folder

**Comment by Tiggles** [comment]
We can't reasonably block the back button for the user. We can block the react-router reacting to URL changes, but that can leave the front-end in an inconsistent state.
