### ISSUE TITLE
Make a user setting for defualt values and sort order

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2818]
User request:

>SUGGESTION: Dear UCloud support, I would like to know if it possible to change the default sorting order for a user or a folder? For example, now the folders are shown intially with 25 entries per page and sorted alphabetically in ascending order. Is it possible to set that it will be, say, 100 entries per page and sorted by access date in descending order? Thank you.

**Comment by Tiggles** [comment]
The itemsPerPage has already been increased to 100, so that's the default already.

I think this can be solved entirely in the frontend.

**Comment by Tiggles** [comment]
This is done for a user, NOT for a specific folder
