### ISSUE TITLE
[2021.3.0] `AppVersion.txt` is not found in production

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2858]
`GET https://dev.cloud.sdu.dk/assets/Assets/AppVersion.txt -> 404 Not Found`

**Comment by Tiggles** [comment]
I assume the issue is related to the additional `/Assets/`. Isn't `/app/` also missing?

**Comment by Tiggles** [comment]
I have created a folder called `/public/` next to `index.html`. The files in here are added to the distribution folder when building the FE at the root level.

I have made an attempt at this, which hopefully works.
