### ISSUE TITLE
Shares should not be possible from projects

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2877]
It is currently possible for a user to chose to share files from within a project. This creates the share in the DB and notifies the reciepient, but  it does not appear in the list of shares for approval.

It should not be possible to initiate the share to begin with
- BACKEND: Make check for project id when attempting to share and throw badrequest.
- FRONTED: Remove frontend share possiblity when in a project.

**Comment by claudiopica** [comment]
@hschu12, @DanThrane I think we should re-discuss about shares within a project. I think we need to support this feature as discussed previously.

**Comment by hschu12** [comment]
@claudiopica I am open for discussion, but currently I do not see a need. Projects have a security aspect with our ACL (groups). Being able to do shares would just make a potential back door to circumvent these read write restrictions . 

If someone want to share a file within a project I would rather have that they copy the file to their personal workspace and share from there or invite the user to the project. 
The copy and share could potentially be made as a single button operation from within the project for the convenience of the users

**Comment by claudiopica** [comment]
@hschu12 there are a number of relevant cases for this. avoiding copying is a major advantage of shares.
ACL can still be "respected" if we only allow admins of the project to create shares.
