### ISSUE TITLE
Improvements to metadata UI

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2882]
It looks like there are a few low-hanging UI improvements which can be made. In particular when comparing multiple versions the UI starts behaving in a strange way.

**Comment by xiroV** [comment]
A few thing I noticed:
 - The "New document" button is visible when a document is open (i.e. when creating a new document). Clicking it does nothing.
 - the "Close document" button is shown when no document is open (but only when a document has been added?). Clicking it opens a new document it seems.
