### ISSUE TITLE
[2021.3.0] Changing file sensitivity not possible before metadata template is applied

### ISSUE THREAD

**Issue by xiroV** [SDU-eScience/UCloud#2914]
It is not possible to change the sensitivity of a file in the files table directly.

However, going to "properties" and adding the UCloud File Sensitivity template works, and afterwards it is possible to change the sensitivity of the file from the files table.

**Comment by Tiggles** [comment]
I can't reproduce this.

How are you trying to change sensitivity?

**Comment by xiroV** [comment]
Seems to work since the push to dev last friday.

I created a folder, then tried to change the sensitivity. Got back the error:
> Template does not exist or you lack the permissions to use it

**Comment by DanThrane** [comment]
Closning this, will re-open if this resurfaces.
