### ISSUE TITLE
[2021.3.0] "Recent Runs" causes the first row of the dashboard to become larger than other cards

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2954]
![image](https://user-images.githubusercontent.com/1782437/143027518-de9692e2-93b2-4115-b5a2-a4dedb17f38f.png)

Note the empty space in the news card

**Comment by Tiggles** [comment]
What is the intended solution to this? Reducing the amount of max recent runs to show?

**Comment by DanThrane** [comment]
I think that is probably the easiest solution, yes.
