### ISSUE TITLE
[2021.3.0] A usage of zero causes issues on the visualization of accounting data

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2976]
Steps to reproduce:

1. Create a public IP address
2. Delete the public IP address
3. View breakdown of product usage

![image](https://user-images.githubusercontent.com/1782437/143040947-4d59e6a5-6f0c-4c1f-8deb-00a103475892.png)

I think we should solve this in the frontend rather than the backend, since the backend is technically correct about the data it responds with.

**Comment by Tiggles** [comment]
@DanThrane following the steps, I'm not getting any thing related to the deleted entry.
