### ISSUE TITLE
[2021.3.0] Jobs does not change state on expiry

### ISSUE THREAD

**Issue by xiroV** [SDU-eScience/UCloud#2977]
Noticed locally, reproduceable on dev.

When a job expires it is kept in the `Running` state. The application itself seems to terminate correctly (the web interface and terminal becomes inaccessible).

**Comment by xiroV** [comment]
Unsure how long it took, but I just noticed my job being "Expired", so the state change happens, just with a rather large delay I assume.

**Comment by DanThrane** [comment]
Caused by #2979
