### ISSUE TITLE
Drive properties visual glitch in messages

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3003]
When first opening the properties page:
![Screenshot from 2021-11-29 13-07-24](https://user-images.githubusercontent.com/44464613/143866252-d697c15a-2ba1-4559-8fe5-ed5e9b9af8cb.png)
After selecting the text with mouse cursor:
![Screenshot from 2021-11-29 13-07-47](https://user-images.githubusercontent.com/44464613/143866426-94b37b29-8114-4dd8-a67f-446fd878c913.png)
After resizing window: 
![Screenshot from 2021-11-29 13-08-04](https://user-images.githubusercontent.com/44464613/143866488-7bd188c9-64fa-40aa-8507-4a710b0aa17a.png)

After having selected the text in the messages box, a square appears. Wen resizing the window after the square appears, characters disappear from the messages box and do not reappear when returning to the original size.

Seen in Firefox 92 on Ubuntu.

**Comment by Tiggles** [comment]
Seems to be related to x-term.

**Comment by DanThrane** [comment]
Resolved by no longer using x-term for these messages.
