### ISSUE TITLE
[2021.3.0] Cannot change sensivity on folders or files before adding metadata

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3006]
Attempting to change sensitivity (by clicking the capital letter in the list view) results in "Template does not exist or you lack the permission to use it" for all 3 levels. Attempting to change to 'Inherit' results in 'Failed to update sensitivity".

After selecting a single folder and pressing the 'Add metadata (beta)' button, then selecting "UCloud File Sensitivity" and setting a level of sensitivity on that folder, changing sensitivity by clicking the capital letter in the list view works.

This metadata can't be deleted again from the same interface:
![Screenshot from 2021-11-29 14-04-25](https://user-images.githubusercontent.com/44464613/143873307-12a937ae-ee79-4cf1-82e6-1a2a2fc9b9b0.png)
Results in 'An error occured. Please reload the page.'

Unsure what the expected behaviour is, but presume this is supposed to be two different ways of achieving the same thing and using either shouldn't depend on the other.

**Comment by DanThrane** [comment]
Confirmed to be a frontend issue. The frontend is, for some reason, not filling out the `templateId`:

```
fetch("https://dev.cloud.sdu.dk/api/files/metadata", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.9",
    "content-type": "application/json; charset=UTF-8",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "sec-gpc": "1"
  },
  "referrerPolicy": "no-referrer",
  "body": "{\"type\":\"bulk\",\"items\":[{\"fileId\":\"/40565/Test\",\"metadata\":{\"changeLog\":\"Test\",\"document\":{\"sensitivity\":\"CONFIDENTIAL\"},\"templateId\":\"\",\"version\":\"1.0.0\"}}]}",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});
````

**Comment by Tiggles** [comment]
To reproduce this issue, I created an entirely new drive, entered the drive and created a folder. Reload the page.

This would consistently not have the Metadata Template until it didn't. Now every folder I create seems to have it, whether or not I have previously done something for the file. 

Solution was to create a function that iterates over result and finds the template in the  `metadataNamespaceApi.browse` call. Seems to work, but seeing as I can't consistently reproduce, this has not been tested that much.
