### ISSUE TITLE
Add metadata 'Favorite' - clicking 'Save' does nothing

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3021]
![Screenshot from 2021-11-30 09-46-43](https://user-images.githubusercontent.com/44464613/144014646-f4386bbc-b025-4700-bcb2-cca817aa80fc.png)

It is very unclear that one needs to click and hold in order to save unless one accidentally holds the click. When clicking on it without holding, the checkmark just flashes.

After having actually saved once, it appears the behaviour changes - and a click now sometimes triggers a 'shake' followed by a message to hold.

Firefox 92 on Ubuntu.

**Comment by xiroV** [comment]
Can't really figure out how to reproduce. I see the problem, but only occasionally. Sometimes the button shake and says "Hold to confirm", other times nothing happens.

**Comment by Tobias-V** [comment]
I think it's a double click that triggers the 'rattle' and message to hold. 
I realise now that 'Hold to confirm' is rather common throughout all of UCloud when deleting things, so it is probably not unreasonable to expect users to try that, although you can return and try again if you forgot to hold when deleting, whereas not saving means you lose something.

**Comment by Tiggles** [comment]
Closing based on last comment
