### ISSUE TITLE
[2021.3.0] Increase spacing between "Filters" and drive selector

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#3022]
Currently we don't have enough space between the "filter" and drive selector, especially when in a modal. I think it would be beneficial to put the filters and sort options on the same row if shown inside of a modal.

**Comment by Tiggles** [comment]
With the `select all` checkbox, I'm not sure that solution is the best approach anymore.

**Comment by DanThrane** [comment]
I agree. I also had to change the header size regardless, for search to be rendered correctly. It looks a lot better now.
