### ISSUE TITLE
[2021.3.0] Update default template for favorites to more understandable

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3025]
![Screenshot from 2021-11-30 09-46-43](https://user-images.githubusercontent.com/44464613/144016881-04c586d6-5bf0-4186-8343-d587ce806f72.png)

The three times it says 'favorite, 'Favorite' and 'Favorite' underneath each other seems a bit redundant and confusing.

**Comment by Tiggles** [comment]
That's related to the metadata template definition. 
The thing that makes most sense to change is likely the description that's currently just "favorite"
