### ISSUE TITLE
[2021.3.0] Favorite metadata 'Delete' on top activity doesn't seem to actually delete anything

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3029]
Delete option on the top activity doesn't seem to do anything. If a new document has just been added and the top activity is named after the document, the top activity will change to 'Deleting document' (with the document remaining). If one then chooses delete on the 'Deleting document' activity, a new 'Deleting document' line will appear underneath, but nothing seems to have changed.

**Comment by xiroV** [comment]
I'm unsure how this is intended to work.

Deleting metadata (at least "Favorite") triggers a deletion of the favorite (as intended). If I remember correctly deletion of the "Deleted document" does not recreate the favorite or update the current state to a previous state (as one might think). So in some way it makes sense that deleting a removal does nothing, but it isn't intuitive.

I'm guessing it would make more sense if, when deleting a deletion of a document, we make a copy of the state prior to the deletion to set as the new active state?
