### ISSUE TITLE
[2021.3.0] Extended allocation of jobs either not stored or not displayed correctly

### ISSUE THREAD

**Issue by xiroV** [SDU-eScience/UCloud#3031]
On dev.

When extending the allocation of a job, the *job expiry* and *time remaining* is updated correctly on the front-end. But refreshing the page resets the expiry and time remaining to the values without the extension.

However, when the time-limit is reached (not including the extension), the job is kept in a running state. 

I'm not completely sure if this means that the extension is not saved (with an additional bug that jobs occasionally doesn't terminate correctly), or if the time allocation just isn't displayed correctly on the frontend.

![image](https://user-images.githubusercontent.com/911284/144021448-7e01fd75-5042-4823-b6de-8ace71d373c1.png)

**Comment by xiroV** [comment]
One of the jobs I used for testing have expired now, which makes me think that the job is extended correctly, but either not updated correctly on the backend, or not displayed correctly on the frontend.

**Comment by DanThrane** [comment]
`expiresAt` appears to never be updated in the orchestrator, but it is correctly updated in the provider. My guess is that this was simply never implemented.
