### ISSUE TITLE
ToggleSet in Browse.tsx seems to have no reference of Page Items until one is added on click

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#3055]
`ToggleSet#checkAll` has no effect since items are considered empty by default.

https://github.com/SDU-eScience/UCloud/blob/storage/frontend-web/webclient/app/Resource/Browse.tsx#L108

**Comment by Tiggles** [comment]
I've made a work-around for this, so it's not pressing.

**Comment by DanThrane** [comment]
will be resolved by the ui rework
