### ISSUE TITLE
[2021.3.0] Shared with me - signify more clearly that the 'Read' field is active permission

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3058]
![Screenshot from 2021-12-01 15-12-21](https://user-images.githubusercontent.com/44464613/144249618-ebaa5002-72b8-4136-bf30-9834e9f97e3b.png)

**Comment by xiroV** [comment]
It isn't a button, but displays the permissions you have on the folder. However, I think it's a valid point that it looks like a button. Maybe we could remove the border, to make it look less like a button?

**Comment by Tiggles** [comment]
I don't agree that it looks like a button. It also shows clicking is disabled on hover, which only is a problem on touch-screen devices.

**Comment by Tobias-V** [comment]
When I hover over it I get a crossed out circle icon, unlike any other element I've hovered over. I took this to mean 'you're not allowed to click this'.

**Comment by Tiggles** [comment]
What do you expect to happen when clicking the field?

**Comment by Tobias-V** [comment]
I presumed this to be a feature for text files, that was disabled because the element is a folder.
I expected it to read the contents of a text file, like there's a preview feature for images.

**Comment by mrlhansen** [comment]
Something else regarding this. To me, it is a bit weird that the "Shared with me" page and "Shared by me" page have different layouts for the list of shares. Also "Decline" is not the right word once it had been "Accepted", it should say "Remove" or something.

**Comment by Tiggles** [comment]
On the second part, I agree, on the first part, it's because you can only be shared a file once, but a file you own you can share with multiple people. So it's a grouping approach and a non-grouped approach.
