### ISSUE TITLE
My Projects page displays 'filters' differently from other pages

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3061]
On the My Projects page one can check 'Show archived', but unlike every other page where a view can be filtered, the 'Filter' text and list of filters does not show.

![Screenshot from 2021-12-01 16-39-03](https://user-images.githubusercontent.com/44464613/144265061-c7341915-5817-4c0b-8fd0-098fa37747ee.png)

Example from files:
![Screenshot from 2021-12-01 16-36-57](https://user-images.githubusercontent.com/44464613/144264735-d0aabf81-0ff8-433f-8e5d-d7c636342cca.png)
Example from shares:
![Screenshot from 2021-12-01 16-40-25](https://user-images.githubusercontent.com/44464613/144265143-b1857c27-03a6-4cac-aeda-55688e1347b0.png)

.

**Comment by DanThrane** [comment]
Like the other project related issues this will be handled in a later release.
