### ISSUE TITLE
[2021.3.0] It is possible to navigate to the active folder from the jobs page

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3062]
The hover effect that makes it apparent something is clickable link (see screenshot below) is missing when hovering over the last part of the path (40619 in the screenshot).

![Screenshot from 2021-12-02 09-34-11](https://user-images.githubusercontent.com/44464613/144386419-006f0348-da4c-4180-9635-4832cf2cc514.png)

**Comment by Tiggles** [comment]
That's intentional, you're not supposed to be able to navigate to the active folder.

**Comment by Tobias-V** [comment]
But the element is clickable. Clicking on 40619 does navigate to that folder.

![Screenshot from 2021-12-02 09-45-59](https://user-images.githubusercontent.com/44464613/144388290-15eb6a3c-7278-4662-9b51-3255ed48692f.png)
.
