### ISSUE TITLE
[2021.3.0] stdout.text unable to retrieve container logs

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3063]
I ran the 'Ubuntu Xfce' app and the stdout.txt file generated by the job reads:

> Unable to retrieve container logs for docker://3222b0321fda0fb8a3565bfdad7033f4828c712308f0257320a72cd6ee9faa84

I presume that means something went wrong.

**Comment by DanThrane** [comment]
Old Kubernetes bug. I would like to fix it but doesn't seem very feasible at the moment.
