### ISSUE TITLE
Add a "Manage My Workspace" entry at the bottom of the dropdown

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3068]
![Screenshot from 2021-12-02 15-52-43](https://user-images.githubusercontent.com/44464613/144445848-bd87743f-c4e1-4fa2-8f91-af42f65d3119.png)

As it is now, it is not obvious how to get to the 'My Workspace' page.

The element, as highlighted on the screenshot, looks like a single element, and it is not very clear that clicking on the icon rather than the text, will open 'My Workspace' rather than the drop down menu.

**Comment by xiroV** [comment]
The icon increases slightly in size on hover, but I agree that it's too subtle. Not sure how we can make it more noticeable, however I think it would make sense to add "My workspace" to the drop-down, like we have "Manage active project" when a project is selected.

**Comment by Tiggles** [comment]
I think that's intentional. Considered a shortcut, not primary functionality.

**Comment by Tobias-V** [comment]
How do you get to the page without using this shortcut? It was the only way I found to navigate there.

**Comment by Tiggles** [comment]
I don't know, and I believe I brought that up back when the change was made.

**Comment by Tobias-V** [comment]
I'm not too concerned about a shortcut being hidden, but the way the UI is now, it seems apparent that there is a workspace one can access - just not how to get there. The feature is also mentioned in the documentation.

I think it would make sense if there was an 'obvious' way to get to the page.
I presume each project has a 'workspace' like this one, and that they're easily accessible through this drop down menu - if 'My Workspace' could be accessed the same way, I think that'd be fine (not sure if this is what Brian suggested).

**Comment by Tiggles** [comment]
Fixed in branch #3304
