### ISSUE TITLE
[2021.3.0] In-progress spinner for file uploads doesn't stop until upload is cleared

### ISSUE THREAD

**Issue by xiroV** [SDU-eScience/UCloud#3084]
After uploading a file to UCloud (tested on dev and locally), the spinner keeps going, even after the file is uploaded.

Tested with a small ~100 kb file.

Refreshing the page warns that there are uploads in progress.

![image](https://user-images.githubusercontent.com/911284/145004531-c07b992d-9678-4ffa-a62a-66ac68f26105.png)

**Comment by DanThrane** [comment]
Clearing the file fixes the issue.

**Comment by Tiggles** [comment]
I'm guessing a `setUploads` call is missing on a upload finish/failure/pause
