### ISSUE TITLE
[2021.3.0] Empty trash-button style doesn't match other buttons in Trash

### ISSUE THREAD

**Issue by xiroV** [SDU-eScience/UCloud#3085]
The empty trash-button appears as a non-primary button it seems. I think it would look better matching the other buttons in the side-bar, although the current style matches the "Move to trash" button from other directories.

![image](https://user-images.githubusercontent.com/911284/145021563-5c699e76-eee7-45cc-b1a3-cb1e1b6d833b.png)

**Comment by Tiggles** [comment]
I think it should be kept as is, as the button form signifies something different compared to those above. Maybe just add a divider between, then?
