### ISSUE TITLE
[2021.3.0] Check that grant autoapproval has all resources

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#3087]
We have had a issue on production where the auto approval seems to miss the setting of quota limits (only has storage credits). This results in autoapprovals that cannot be approved since the quota is always set to zero.

This is just to check that this is not possible in the new version of UCloud.

Ask Henrik for more info if neccesary

**Comment by DanThrane** [comment]
Shouldn't be an issue anymore, now that we have changed how quotas work.
