### ISSUE TITLE
[2021.3.0] Right-clicking on a row has actions only for that row, even if other rows are selected.

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#3090]
I think it's a bit confusing that selecting 2 rows and right-clicking on one only does the action on that one.

Either: 
- Show the file-name the action is done for
- Clear toggled on right-click

<img width="1490" alt="Screenshot 2021-12-07 at 14 53 42" src="https://user-images.githubusercontent.com/7610257/145041978-1b3157f6-1be0-420e-a6e4-1e21eea2288b.png">

**Comment by Tiggles** [comment]
MacOS behaviour for comparison

<img width="506" alt="Screenshot 2021-12-07 at 14 56 16" src="https://user-images.githubusercontent.com/7610257/145042081-f8196dae-22d2-40e5-b6fa-4dc4b7c7a434.png">

**Comment by DanThrane** [comment]
Should definitely show options for all of them. I think this is a regression bug since I am pretty sure I implemented this at some point.
