### ISSUE TITLE
[2021.3.0] No warning for deletion of drives with contents

### ISSUE THREAD

**Issue by xiroV** [SDU-eScience/UCloud#3096]
Not really an issue, but maybe something we should consider a solution for.

Drives can be deleted, even if there's files in the drive, with no warning that the contents aren't recoverable. Deleting files inside a drive is recoverable until the trash is emptied.

**Comment by DanThrane** [comment]
Maybe we should do something like this? 
![image](https://user-images.githubusercontent.com/1782437/145157646-ad04afc0-bf14-45f8-aff6-102a9b7df286.png)

**Comment by Tiggles** [comment]
So do we do confirm button to get to the modal first and then the `Type Drive name to confirm` or just a normal button that leads to the modal?

**Comment by DanThrane** [comment]
I think this would work.
