### ISSUE TITLE
Shares are filterable through `_ucloud` user.

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#3097]
Not sure if this should be considered a bug or even unintended behaviour, but filtering by `Created by` using `_ucloud` shows every share when viewing drives.

![image](https://user-images.githubusercontent.com/7610257/145060672-d5f50d35-feea-4882-92f8-3a8e7474b281.png)

**Comment by Tiggles** [comment]
`_ucloud` is correct for the backend, but kind of misleading for the end-user. You can't filter by who created the folder/share initially, which can be confusing.

**Comment by xiroV** [comment]
I agree, but as far as I can see, this information is not a part of the resource.

**Comment by Tiggles** [comment]
Seems like it isn't, but disallowing searching for _cloud seems like an option, but that's an amount of unnecessary overhead when searching.

**Comment by DanThrane** [comment]
I don't really mind it showing up while filtering. But we should probably hide it in the UI, that is, from the properties page.

**Comment by Tiggles** [comment]
Closing. Will create a new issue for the properties part.
