### ISSUE TITLE
[2021.3.0] The search string when searching for licenses seems to be ignored.

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#3104]
Searching for "MATLAB" yields all of these results
![image](https://user-images.githubusercontent.com/7610257/145183831-4603e805-24d4-4660-8e78-5716bef7b078.png)

**Comment by DanThrane** [comment]
Looks like search isn't actually supported on the backend at the moment. I'll suggest we just disable this on the frontend.
