### ISSUE TITLE
Sorting by creation date would be more intuitive if defaulting to descending order

### ISSUE THREAD

**Issue by xiroV** [SDU-eScience/UCloud#3108]
Just a minor thought.

When sorting by name, it makes sense that the results appear in ascending order. However if I choose "Sort by Created date" I would assume that it's because the user wants to see the newest entries first (i.e. descending order).

I know users can simply choose the sort direction afterwards, but for convenience, I think it makes sense.

**Comment by Tiggles** [comment]
I don't think this is necessarily true. You could just as easily want to find the oldest file in a folder.

**Comment by Tiggles** [comment]
I think there's reasons for having both, so I don't think it makes sense to default to any one. Closing for now.
