### ISSUE TITLE
Invalid shares should show a meaningful error message

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#3121]
Steps to reproduce:

1. Share a file
2. Accept the share
3. Delete the share through an application
4. The share is no longer valid, but still present in the user interface

The user interface should make it clear that the files belonging to this share are gone. It should provide an easy way of invalidating the share entirely. We should be able to validate if a share is valid by retrieving the file which has the share, if we get nothing back, then the share is probably not valid.

**Comment by Tiggles** [comment]
The way ResourceBrowse works makes it kind of hard to couple MainTitle navigation to operations. If we want to disable navigation in the MainTitle as well as hiding operations, we might need to make the call multiple times, as no meaningful prop to denote that the share is outdated is currently part of it.

**Comment by Tiggles** [comment]
Fixed with ui-redesign
