### ISSUE TITLE
Apps shows filecollection id instead of name when mounted

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#3184]
When mounting a drive created after the update to an app, it will show the filecollection ID inside the app.

This is expected since this is the actual folder name on the filesystem, however not how the folder is represented on UCloud which results in confusion. 
We should attempt to use the name of the file collection instead of the ID when mounting.

**Comment by mrlhansen** [comment]
It is currently possible to create multiple drives with the same name (which from a user perspective in itself is a bit confusing), but it will cause problems when trying to mount multiple identically named drives inside a container.
