### ISSUE TITLE
Previews of .docx in file-properties

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#3221]
Some users have requested being able to preview .docx files on UCloud, which would only require read-only viewing.

One solution would be to allow previewing of .docx by converting them to PDFs for previews, but as I remember the backend, it just uses the download endpoint, so a something like a `convertToPDF` flag would be needed in the download request.

**Comment by Tiggles** [comment]
@DanThrane Any info on how viable this would be?

**Comment by emolinaro** [comment]
There is group from SAMF that wants to use UCloud to store sensitive data collected in the form of Word documents. If they decide to use UCloud, they would like to preview these documents rather than run an app like LibreOffice to read them.

**Comment by DanThrane** [comment]
Our best bet would be to run libreoffice and even this isn't particularly good, since it isn't actually fully compatible with documents created by Word.

**Comment by Tiggles** [comment]
I guess the easiest approach is to download the file instead? But that requires some software to be able to preview it.

**Comment by claudiopica** [comment]
@Tiggles that is not an option for sensitive files. What is the current strategy for previews on UCloud?
there are libraries to render docx files to html, e.g. https://github.com/zVolodymyr/docxjs ( not perfect however...) .
