### ISSUE TITLE
Email notification on downtime announcenments

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#3249]
User Request: 
A researcher ought to be able to subscribe to an email notification about service critical events to their projects, such as a UCloud upgrade a month ago, or the planned restart a few days ago. If I have Type 1 projects, type 1 notifications would reach me. If I only have Type 2, (in the long run, once the types are unified), I should only get Type 2 relevant notifications. Or at least I should be able to choose what notifications to subscribe to.

**Comment by DanThrane** [comment]
Not planned at the moment, but I think we want to further improve our status pages. This should be able to improve this situation.
