### ISSUE TITLE
Stopping application twice triggers failure

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3272]
When you stop an application (hold to confirm) it says 'Done', but if you click it again you can repeat the process. This causes the job to end with failure rather than success.

Tested with: Charticulator v2.0.4 and JupyterLab v3.1.4

Edit: To clarify, this is on the properties page of the job(?), such as https://cloud.sdu.dk/app/jobs/properties/52150?app=jupyter-all-spark

**Comment by DanThrane** [comment]
Fixed on `devel-sync`. Will be deployed together with #2404.
