### ISSUE TITLE
[ui] Project resource view re-work

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#3288]
- Sort by category
- Create a higher level of view of multiple products:
     - Collapsed cards
     - Aggregate usage, show as progress bar
     - Show EARLIEST expiration date with accompanying text
     - Accordion
     - ~Subdivide by GPU/CPU~
     - Subdivide by compute and storage

**Comment by claudiopica** [comment]
Hi @Tiggles it's not needed to subdivide by CPU/GPU right now. Let's just aggregate all compute resources together.

**Comment by Tiggles** [comment]
![image](https://user-images.githubusercontent.com/7610257/156141776-ac6dace7-4c58-4839-a441-430374c2f34a.png)
`Other` has a subheader that shouldn't be there
