### ISSUE TITLE
[ui] FileTable fixes

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#3289]
- [x] Sensitivity placement should be fixed.
- [x] ~Re-add (if possible) Quicklaunch shortcut. (Called 'Open With')~
- Only show on hover?
- [x] Preview button. 
- What should be previewable and what shouldn't?
- Only show on hover?

**Comment by Tiggles** [comment]
Regarding #2 and #3, I'm not sure how viable quick-launch is to only show for some. We could look at file extensions as the cheapest solution, but that can't guarantee that the file in question can be used.

#3 could just redirect to Properties, but scroll down to the preview.
@DanThrane, @claudiopica

**Comment by claudiopica** [comment]
Hi @Tiggles, for the quicklaunch icon the idea is to display it for all as a shortcut to "open with".

**Comment by DanThrane** [comment]
Regarding quick-launch, I would simply do something similar to what "Open with..." does. I think we should be able to query for all visible files in one query using this https://github.com/SDU-eScience/ucloud/blob/e06e68b0e0f021d3898f1b5e954dba1d594ae47f/backend/app-store-service/api/src/commonMain/kotlin/api/AppStore.kt#L804

The previous button should probably just display if we are able to preview it. It should just scroll to the preview pane. I don't think it makes sense to have multiple pages for the same functionality.

**Comment by Tiggles** [comment]
> Hi @Tiggles, for the quicklaunch icon the idea is to display it for all as a shortcut to "open with".

I was mostly thinking about what rows to show it for, and which it should be omitted from. But the endpoindt Dan linked should solve my issue.

**Comment by claudiopica** [comment]
are we sure it's not too slow? how does that work with pagination?

**Comment by Tiggles** [comment]
We're gonna experience some overhead to do this, either way. But I'm not sure how big of an issue this will be, if we can't query every file at once.
