### ISSUE TITLE
Cannot edit suballocation

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3303]
Getting the following error when attempting to edit a suballocation:
Row 97: New allocation period is invalid. It doesn't overlap with descendants.

Steps to reproduce:
Allocate 50 GB of u1-cephfs to a subproject.
Edit start date, end date or amount
Press 'Save'

JIRA reference: TICKET-952

**Comment by DanThrane** [comment]
Fixed in https://github.com/SDU-eScience/UCloud/commit/a8900a17f18ef852a671d75bc8ff8425b6c02dee

Fix confirmed by Federica.
