### ISSUE TITLE
Cannot implement default value for an integer/float/string variable

### ISSUE THREAD

**Issue by emolinaro** [SDU-eScience/UCloud#3308]
The following error is shown when the application YAML file is uploaded on UCloud:
```
dk.sdu.cloud.app.store.api.ApplicationParameter$Integer["defaultValue"]. Cannot contruct instance of
`kotlinx.serialization.json.JsonElement` (no Creators, like default construct, exist): abstract types neither need to
be mapped to concrete types, have custom deserializer, or contain additional type information at ...
```
Similarly for `floating_point` and `text` variable types.

**Comment by emolinaro** [comment]
[nf-core-ampliseq-app.yml.zip](https://github.com/SDU-eScience/UCloud/files/8107542/nf-core-ampliseq-app.yml.zip)

**Comment by Tobias-V** [comment]
In the yaml file in the zip, the defaultValue variable contains a single value, however the error is also present when defaultValue is a k/v pair as the example in the documentation: https://github.com/SDU-eScience/UCloud/blob/master/docs/developer-guide/orchestration/compute/appstore/apps.md

```
defaultValue:
      type: integer
      value: 0
```
