### ISSUE TITLE
Add more information to subproject page

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#3311]
User request:
There could be additional columns, e.g., reference ID that the project author should use when referring to UCloud in publications, PI name, start and stop date for project resources, etc.

**Comment by claudiopica** [comment]
@hschu12 noted.
we are re-doing this page/section completely with @Tiggles , so no need to act on this issue separately.

**Comment by Tiggles** [comment]
![image](https://user-images.githubusercontent.com/7610257/156519652-cbd027ec-e706-4ff1-800d-3b1865779600.png)
Is it the same page @hschu12 is referring to? I'm making changes to 'Resource and Usage', not the 'Subprojects' one.

**Comment by claudiopica** [comment]
@Tiggles, @hschu12 it will also affect subprojects
