### ISSUE TITLE
Virtual machine based on Debian distribution

### ISSUE THREAD

**Issue by emolinaro** [SDU-eScience/UCloud#3314]
The RUC front office asked if it is possible to run VM instances based on Debian distribution.

Their colleagues maintain a Debian repository with all packages required for research and it would make it easier for them to work with a VM based on Debian instead of Ubuntu.

**Comment by DanThrane** [comment]
Not a UCloud (the software) issue. The software is ready to support this once the VM base images are ready at AAU.
