### ISSUE TITLE
Files are not returned in the correct sort order

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#3336]
The order seems to go by folder before file, which isn't ideal when specifically sorting by size.
<img width="1008" alt="Screenshot 2022-03-10 at 11 02 04" src="https://user-images.githubusercontent.com/7610257/157651925-9efcf8e4-79d0-4d2d-b790-532ae946472c.png">

Seems likely that his is because we are sorting by `modifiedAt` but the date shown is `createdAt`.
<img width="1008" alt="Screenshot 2022-03-10 at 11 00 42" src="https://user-images.githubusercontent.com/7610257/157651935-4dfbe172-1068-41f8-a73e-0c8ad77c5aa1.png">

**Comment by Tobias-V** [comment]
![Screenshot from 2022-04-28 13-37-48](https://user-images.githubusercontent.com/44464613/165743940-44a6f993-080a-4ec6-9392-810725b8da3d.png)
Is this weird sorting explained by using modifiedAt rather than createdAt?

**Comment by DanThrane** [comment]
This was fixed a while back but we forgot to close the issue.
