### ISSUE TITLE
Possibility for Project PIs and Admins to search for users (resource related)

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#3348]
We have requests for the possiblity to search for a user and be returned a list of projects that this user is in (along their role in the project if possible).  

This should only return projects where the users searched for is part of and if they are funded by the active project directly.

This will remove the need to search through old emails or other conversations to locate a projectID when asked for more resources outside of the grant system. 

Given the example below (Green is where the user search for is part of. Arrows show allocation of resources):
If search for user from P1: returns P2 and P3
If search for user from P2: returns P3 and P6
If search for user from P4 returns P7

<img width="434" alt="Screenshot 2022-03-16 at 09 42 01" src="https://user-images.githubusercontent.com/10943804/158550548-e5283ec3-010f-4706-a44c-bbbed0b6f3c9.png">

**Comment by claudiopica** [comment]
@hschu12 who is requesting this feature and what authority the entity will have to require this information?

In any case this is very LOW_PRIORITY right now.

**Comment by hschu12** [comment]
👍  This is something I have talked with Emiliano about. And I agree that this is Low Priority

**Comment by emolinaro** [comment]
It was requested by CBS front office.

**Comment by claudiopica** [comment]
@emolinaro we should be careful about these requests. the problem is that e.g. some CBS users can have projects on their own or projects that have been allocated by someone else, or participating in projects allocated by other FOs, etc

**Comment by emolinaro** [comment]
I think this feature would be mostly useful for administrators of  projects that distribute resources to a large number of subprojects. In particular, administrators of type - 1 root projects. 
Quite often it happens that user asks for support without providing information about the project. If the administrator can get the  project name without asking the user directly, this would improve the interaction with the user.

**Comment by claudiopica** [comment]
@project information can easily be attached to support request.
We are also reworking the resource overview with @Tiggles
