### ISSUE TITLE
Frontend does not report any error when a job folder can not be stored

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3352]
Submitting a job with insufficient available storage does 'nothing'. No error is reported to the user, and seemingly nothing happens.

JIRA reference: Ticket-1019
User tried to submit jobs from both Firefox and Chromium (Ubuntu) and nothing happened, supposedly the backend reports that the job folder can not be stored.

Possible issue with '402 - Payment required' as well. See JIRA Ticket-1018 for reference.

**Comment by Tiggles** [comment]
The backend no longer responds with `errorCode`, which is why nothing is rendered.

**Comment by Tiggles** [comment]
Frontend expects one of these
```
const MISSING_COMPUTE_CREDITS = "NOT_ENOUGH_COMPUTE_CREDITS";
const MISSING_STORAGE_CREDITS = "NOT_ENOUGH_STORAGE_CREDITS";
const EXCEEDED_STORAGE_QUOTA = "NOT_ENOUGH_STORAGE_QUOTA";
const NOT_ENOUGH_LICENSE_CREDITS = "NOT_ENOUGH_LICENSE_CREDITS";
```
