### ISSUE TITLE
Drive owner avatar does not match actual avatar of the user

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3408]
Screenshot is from dev, but the same issue is present in production
![Screenshot from 2022-04-27 14-58-26](https://user-images.githubusercontent.com/44464613/165523950-9c0711fb-a580-4b1d-9c3e-772d7b3b7519.png)
.

**Comment by Tiggles** [comment]
Without looking into it, I would assume that the avatar-cache isn't being updated correctly, or the responses aren't being used.

**Comment by Tobias-V** [comment]
I see the same avatar on production and dev, so I presume this is a default avatar of some sort.
