### ISSUE TITLE
Mails to support take up to an hour to send

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3409]
It can take over an hour from a ticket is created in UCloud (per the Slack timestamp) before the e-mail arrives in our mailbox. 
The mail does not appear to be stuck in our outgoing mailserver, so I would suspect UCloud's postfix server to be the one causing the delay.

**Comment by DanThrane** [comment]
Nothing obviously wrong based on the logs. But I think you are probably right that our postfix server could be the issue.

**Comment by Tobias-V** [comment]
Can take significantly longer than an hour..
Two e-mails have be sent today, and the first one was received by our outgoing mailserver immediately, and the other one took two and a half hours.
