### ISSUE TITLE
Create an input parameter which can use a list of files

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#3418]
Some batch jobs can use multiple input files when running. It would be nice to have the possiblity to select multiple files in an input file parameter. Could be a list of files that also allows just a single element.

**Comment by DanThrane** [comment]
I have changed the title since I believe this should be a new parameter which is explicitly mentioned in the application specification. While convenient to just have all apps work like this, I feel it will break quite a lot.

**Comment by Tiggles** [comment]
Duplicate of #3632
