### ISSUE TITLE
Feature request: Add members to a project using their e-mail address

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3419]
Since there is no way to obtain a username before a user has logged in, I think it should be possible to add members to a project, using their e-mail address - even before the user has ever logged into UCloud.

A possible scenario where this would be useful, is if someone uses UCloud for teaching and they want to set up permissions/project for their students beforehand, as to not waste valuable teaching time.

JIRA reference: TICKET-1139

**Comment by claudiopica** [comment]
a simpler (better?) alternative that was already discussed is to create an invitation link to the project.
@DanThrane is there already an issue open for this feature?

**Comment by DanThrane** [comment]
There is now. #3421 should be sufficient to deal with the feature requested here, I don't think email is required for the first iteration and we can always expand it to include email.

**Comment by Tobias-V** [comment]
I'm suggesting this approach because it will presumable allow the PI to perform all organizational tasks without user interaction.

The way I understand #3421, user interaction is required before a PI is able to organise the members in groups (the invitation needs to be accepted before a user can be added to groups).
