### ISSUE TITLE
[sync] Sync UI buttons available for shares, but don't add anything

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3430]
![Screenshot from 2022-05-05 14-00-58](https://user-images.githubusercontent.com/44464613/166918972-c41c2c0b-0b0a-4fcd-8477-7b00e3c54e46.png)

When pressing 'Add to sync' the UI acts as if it was added and the button changes, but it isn't actually added.

**Comment by DanThrane** [comment]
@xiroV Not 100% sure that this approach will even work for shares, we might need to just disable for normal shares.
