### ISSUE TITLE
Notify user in some way that an allocation will exceed allocation balance

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#3516]
By design, a user can allocate an arbitrary amount of resources from an allocation, and as long as those resources are not utilized, no issues/blocking of uploads/running apps will occur.

But seeing how exceeding the allocated amount isn't communicated at allocation-time, this could surprise the allocation-giver later down the line.

How do we communicate that an allocation will exceed the amount of resources available from the parent allocation, but that this is allowed intended behavior?

**Comment by claudiopica** [comment]
@Tiggles which user do you want to notify?

**Comment by emolinaro** [comment]
We received several tickets related to overallocation of resources in subprojects.

**Comment by DanThrane** [comment]
Stale issue, potentially solved by upcoming merge of #3595
