### ISSUE TITLE
Communicate clearly that different cards for same product type don't share info on their respective products

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#3517]
The color green is used across both of these, despite them being not being related. This might be confusing for the user.

<img width="421" alt="Screenshot 2022-06-21 at 10 21 19" src="https://user-images.githubusercontent.com/7610257/174753670-d7bcbf00-7055-4101-ac9e-5705caaa10c6.png">

**Comment by DanThrane** [comment]
Will be fixed in 2024.1.0
