### ISSUE TITLE
App search results with many hits can only display the first page

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3549]
JIRA reference: TICKET-1286

If an app search results in more than one page, switching to the second page results in a 'Not found' message.

Below are the URLs from testing with a search for R. It looks to me as if the search term is being dropped from the URL parameters - in addition it looks like it's not getting the page right either.

https://cloud.sdu.dk/app/applications/search?q=R

https://cloud.sdu.dk/app/search/applications?query=&tags=&showAllVersions=false&page=1&itemsPerPage=25

Edit: I can't get it to display anything when modifying the bottom URL, so it's probably safe to say that my understanding of this issue is not correct.

**Comment by Tiggles** [comment]
'Not Found' is our 404 page, so it's pointing old url that used to lead to a component.
