### ISSUE TITLE
Implement maxUsableBalance val

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#3595]
When retrieving and wallet or allocation, then also calculate what is the maximum amount of resources actually avalable.
Eventhough you have been given an allocation of 1000DKK then the parent project might only have 200 DKK available through that particullar allocation. This results in confusion because the user might think they have 800 left when the frontend starts complaining that there are not enough resources and it is in fact the parent project that are out of resources.

**Comment by Tiggles** [comment]
Related to #3516
