### ISSUE TITLE
Ultrawide screen options are hard to select

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3629]
![Screenshot from 2022-08-29 12-30-03](https://user-images.githubusercontent.com/44464613/187181704-67673f5c-8e64-4fb9-aba7-380a8fb7bc8e.png)

It's difficult to select the right options on a 21:9 (3440 x 1440) resolution.

**Comment by DanThrane** [comment]
Fixed in 2024.1.0
