### ISSUE TITLE
Rounding error for Core Hour products

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#3635]
Reported by @claudiopica

> e.g. I entered 200 core*hours (these are the new product categories, but it might work also for DKK) and press the sumbit button
> on the approval page it is shown as 198 core*hours

**Comment by Tiggles** [comment]
Can't reproduce on FireFox. This might be a Chrome/Blink issue. Having an input field active and scrolling down reduces the value in the input field on Chrome/Blink (tested on Brave).

**Comment by claudiopica** [comment]
@Tiggles that could be the reason. On Chrome this happens only when the field is active and you start the scrolling while the mouse is hovering on the active input field

**Comment by Tiggles** [comment]
Closing as I don't think this is enough of an issue to override default `<input>` behavior.
