### ISSUE TITLE
x-term copy pasting via keyboard shortcuts on Linux/Windows

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3642]
Some apps print an output that the user needs to copy and paste into a different window.

Supposedly Mac users can select the output and copy it using keyboard commands, but the same is not possible for Windows and Linux users. Is this something that can be improved upon?
UCloud-Apps reference: 833

**Comment by DanThrane** [comment]
Resolved on `dev-2024-1-0` by not using xterm-js for log output.
