### ISSUE TITLE
Update help text/link on frontpage

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3644]
![Screenshot from 2022-09-06 13-38-38](https://user-images.githubusercontent.com/44464613/188627921-ce6bfca2-7e5c-4f21-97c1-cbfe677acc6a.png)

The current e-mail address is for the SDU HPC front office, we should link to the following webpage instead: https://www.deic.dk/en/Front-Office

If we want to do fancy localisation, there's also this version: https://www.deic.dk/da/Front-Office

**Comment by Tobias-V** [comment]
@claudiopica it is something I discussed with @emolinaro prior to creating the issue.

I want it changed, because contacting servicedesk@escience.sdu.dk provides non SDU users with a user experience that can be outright negative.

Creating the ticket in JIRA for it to be automatically processed and closed and the information forwarded to their local front office, is not a positive user experience. A user referred to this experience as a 'slap in the face'.

I'm not suggesting we link to the front office webpage because it is a good solution, but I think this is better than the current alternative.

**Comment by claudiopica** [comment]
why is it better? one user complaining is not enough to conclude the alternative is better. The suggested alternative is that we send them to a webpage where the user by herself must find the right email and write to them, ie. the end result is the same but with a lot of wasted time for the user. How is this better?

**Comment by claudiopica** [comment]
So I suggested we don't change this unless a better alternative is found.
