### ISSUE TITLE
Issues with showing job logs and interfaces

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3683]
The problem has been seen in Firefox (on Ubuntu), Chrome (on Mac) and Safari.

Opening the same page in a clean session or a different browser, usually solves the problem.

We first witnessed this about ~3 weeks ago (Chrome on Mac).

I've noticed 4 different ways this can glitch. The below screenshots and glitches are produced on a freshly installed Ubuntu 20.04 machine.

![Screenshot from 2022-09-21 15-57-36](https://user-images.githubusercontent.com/44464613/191525800-b34d1747-7aba-4da6-9735-a744b25c6e1f.png)

In the first case the prompt starts empty, and any output that is generated while the prompt is shown, appears (F5 results in a new blank prompt). The screenshot shows the output generated after pressing open interface.

![Screenshot from 2022-09-21 15-58-50](https://user-images.githubusercontent.com/44464613/191526206-c8e65f8d-8793-4553-9507-4987f59b8f82.png)

In the second case, the prompt does not appear as the app is queued up. When the app starts, all prompts are working fine.

![Screenshot from 2022-09-21 15-59-14](https://user-images.githubusercontent.com/44464613/191526522-b0d1abb9-f8fb-41b6-a500-8521ce48ea87.png)

In the third case, the prompt does not show anything at all, even if generating new output.

![Screenshot from 2022-09-21 15-59-33](https://user-images.githubusercontent.com/44464613/191526777-2a26388f-0b5c-40c7-b4f3-f3baef382aae.png)

In the forth case, pressing open interface results in a blank page.

I was able to produce this behavior by starting the various coder apps numerous time, but we have seen the behaviour with other apps as well.

**Comment by Tobias-V** [comment]
I haven't left the interface open long enough before to know is this is consistent, but the interface from the 4th screenshot just loaded as I'd posted this, after about ~20 minutes of waiting.
In other testing, the interface has worked immediately when opened from a new browser.

**Comment by DanThrane** [comment]
Resolved on `dev-2024-1-0`.
