### ISSUE TITLE
[hippo] Confusing error message when navigating to a folder user lacks permissions for

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#3695]
This results in a frontend bug and a generic "Not found" error  message

**Comment by Tiggles** [comment]
I can't find "Not Found" other than in `Properties.tsx` and `XHRUtils.ts`, is this the message from the backend or does it come from the frontend?

**Comment by Tiggles** [comment]
This is trying to access a drive directly that the user has no access to.
https://user-images.githubusercontent.com/7610257/202398440-86072ab9-c035-4ce4-a055-439905287115.mov

**Comment by DanThrane** [comment]
No longer an issue.
