### ISSUE TITLE
Allow multiple files to be selected in file browser when uploading files

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#3708]
You are allowed to drag and drop multiple files, but not select multiple files when selecting in the file browser.

We may have disabled this in the past because selecting a folder uploaded the content, not the folder with the contents, confusing users.

Investigate what allowing multiple files would lead to, e.g. if above issue would re-appear.

**Comment by DanThrane** [comment]
Fixed in 2024.1.0
