### ISSUE TITLE
Minor issue with pagination on Suballocations. State is stuck.

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#3723]
Can result in duplicates. Are gone after hard refresh.

**Comment by Tiggles** [comment]
@hschu12 Was 'SubBrowsers' meant as 'Suballocations'?

**Comment by hschu12** [comment]
Yes browse sub allocations page/call. On devel-accounting branch

**Comment by Tiggles** [comment]
I believe this is solved with the ProjectV2 rewrite, but I have an improvement.
