### ISSUE TITLE
Syncthing crahes with DB exception when attempting to add folder

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#3738]
For Milos and Federica this seems to happen when they are adding a folder to Synchting resulting in a 500 internal server error.

I cloud.calls.server.RpcServer - com.github.jasync.sql.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=[(Severity, ERROR), (V, ERROR), (SQLSTATE, 42P10), (Message, there is no unique or exclusion constraint matching the ON CONFLICT specification), (File, plancat.c), (Line, 824), (Routine, infer_arbiter_indexes)])

My guess is that this is a thing that happens when resetting or starting from scratch with a synthing instance and during the clean up there is something left behind that causes a conflict in the DB.

**Comment by Tobias-V** [comment]
Possible new instance of this in JIRA TICKET-1612 (closed).

**Comment by DanThrane** [comment]
Fixed
