### ISSUE TITLE
Allocations startdays in grant is 00:00:00

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#3763]
When accepting a grant the start dates of allocations is 00:00:00. This results in "allocation not allowed" due to start being before start of parent which might be generated with now()

16/11/2022 - 00:00:00 CET
16/11/2022 - 15:03:44 CET
14:54:18.982 () WARNING cloud.calls.server.RpcServer - grant.updateApplicationState BulkRequest(items=[UpdateApplicationState(applicationId=1, newState=APPROVED, notify=true)]) Internal server error:
dk.sdu.cloud.calls.RPCException: Allocation period is outside of allowed range. It must be between 16/11/2022 - 15:03:44 CET and 17/08/+292278994 - 09:12:55 CEST.

**Comment by DanThrane** [comment]
I would just make sure that the parent, and all other allocations are also created at the start of the day,
