### ISSUE TITLE
Jobs for UCloud compute plugin on dev don't expire

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3773]
When starting a job on dev, timeAllocation seems to be ignored.

When the timer reaches 00:00, the job does not end.

Tested with three different apps on standard-cpu-1 type.

**Comment by DanThrane** [comment]
This is mostly a comment for myself.

To my knowledge this only affects the IM version of the provider. As a result, this won't be urgent until we intended to deploy it. At the moment, we intended to do this along with the k3s deployment.
