### ISSUE TITLE
`share` shows up as a selectable when creating a drive

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#3777]
<img width="836" alt="Screenshot 2022-11-28 at 16 20 18" src="https://user-images.githubusercontent.com/7610257/204314837-2aee0ca6-f865-4db1-a16f-4663c0338de8.png">

**Comment by DanThrane** [comment]
I wouldn't rule out that this is a backend bug.

**Comment by DanThrane** [comment]
The UCloud storage plugin is incorrectly returning `usersCanCreate` for the share drive product.
