### ISSUE TITLE
Refresh on Ingoing Applications page not working

### ISSUE THREAD

**Issue by xiroV** [SDU-eScience/UCloud#3785]
Found on dev. Unsure if already fixed.

Refresh-button on Project Dashboard -> Grant Applications (Ingoing Applications) page empties the result list.

**Comment by Tiggles** [comment]
It's not fixed, the refresh function is missing the `projectOverride`.

**Comment by xiroV** [comment]
Yes, the title and description is actually misleading. It seems like I might have changed project by accident, which led to the refresh-button not working anymore. Still a bug, but different from what I wrote.
