### ISSUE TITLE
Inline resource creation: text field hard to re-activate

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3796]
![Screenshot from 2022-12-06 12-45-52](https://user-images.githubusercontent.com/44464613/205906493-081e7431-cd4b-4525-814d-7eb892b111fe.png)

If one manages to leave the text field while creating a new folder, it is not possible to enter the text field again by clicking anywhere on the row, only clicking on the first ~quarter of the row will activate the text field.

**Comment by Tiggles** [comment]
Turns out, this was already solved using 
```
.row-left-content:has(> form) {
    width: 100%;
}
```
However, the `:has`-pseudo class is not yet fully supported on Firefox, so this should work on pretty much everything else.
