### ISSUE TITLE
Missing explanation when no storage resources are available

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#3804]
In the event that a user has no storage resource from a provider, some weird behavior can occur for drives.
I believe these should never happen on the production system, so I'm not sure we should spend time fixing them, but I think it's worth bringing up at least.

No create drive button, and no explanation as to why.
![Screenshot 2022-12-07 at 10-40-32 UCloud Drives](https://user-images.githubusercontent.com/7610257/206418196-cb92aa6c-ce00-42b9-a022-f16ab986986e.png)

No drives, shows up as an empty dropdown with none selected.
![Screenshot 2022-12-07 at 10-40-02 UCloud Coder C 1 64 2](https://user-images.githubusercontent.com/7610257/206418607-f5dfb3b9-fbd8-45d4-9570-b61189ed2389.png)

**Comment by DanThrane** [comment]
> I believe these should never happen on the production system

It is possible on the production system already. The most common case would be if someone applies for the AAU machines only. That way the project only receives compute credits and no storage balance for any provider.
