### ISSUE TITLE
'Not shared with any group' issue

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3810]
Some folders will say 'Not shared with any group' despite having group permissions set.

Attached screenshots of a folder with this issue.
![image](https://user-images.githubusercontent.com/44464613/207016970-c58390db-260e-4d24-bc53-7a3b20309afd.png)

![image](https://user-images.githubusercontent.com/44464613/207016795-42c9a956-c0bd-4ff7-977b-2b8b7880aaaa.png)

**Comment by DanThrane** [comment]
Confirmed to be a frontend issue. The backend correctly returns information about the permissions (IDs redacted):

```json
{
  "id": "RESOURCEID",
  "specification": {
    "title": "App Tests",
    "product": {
      "id": "u1-cephfs",
      "category": "u1-cephfs",
      "provider": "ucloud"
    }
  },
  "createdAt": 0,
  "status": {
    "resolvedSupport": null,
    "resolvedProduct": null
  },
  "updates": [],
  "owner": {
    "createdBy": "USERNAME",
    "project": "PROJECTID"
  },
  "permissions": {
    "myself": [
      "ADMIN"
    ],
    "others": [
      {
        "entity": {
          "type": "project_group",
          "projectId": "PROJECTID",
          "group": "GROUPNAME"
        },
        "permissions": [
          "EDIT",
          "READ"
        ]
      }
    ]
  },
  "providerGeneratedId": "p-PROJECTID/App Tests"
}
```

**Comment by Tiggles** [comment]
I'm having a hard time reproducing this on `dev`. Is the original example from `production`?

**Comment by Tobias-V** [comment]
This is from the UCloud-Apps project on production - most of our drives fail to show that they're being shared.

**Comment by Tiggles** [comment]
Can you add me to the project? As a user.
