### ISSUE TITLE
Accounting inconsistencies/case for testing

### ISSUE THREAD

**Issue by xiroV** [SDU-eScience/UCloud#3815]
I've noticed some inconsistencies/bugs related to our accounting system. Some might have already been addressed in #3803, but for future reference/testing of the new system, I'll leave this here.

Procedure:
 - Applied and accepted grant for 5 GB storage quota and 5 DKK cpu usage (both on k8)
 - Started job for 1 hour on cpu-2 (0,19 DKK/hour).
 
 The next day I noticed that the job had not terminated, and was still in the "Running" state (covered in #3773). I cannot rule out that some of the following issues are related to the existing issue.
 
 Problems:
  - Project -> Resource Allocations
    - Storage shows "12/5 GB". Checking both on UCloud and the container, the actual usage is <1 MB.
    - CPU shows "<0,01 / <0,01 kDKK". The card shows "<0,01 DKK used" and "5 DKK allocated". The correct usage would be "0,19 DKK" or more.
  - Dashboard Resource Allocations card
    - Shows "4,99 DKK" for cpu, but nothing about Storage.
  - Project -> Resource Usage
    - Shows "0,01 DKK used" for cpu, and "No usage found" for storage.

**Comment by hschu12** [comment]
Seems to work after new accounting
