### ISSUE TITLE
Slurm jobs missing logs

### ISSUE THREAD

**Issue by xiroV** [SDU-eScience/UCloud#3821]
During test of our upcoming release some users reported that the beginning of the log output sometimes didn't appear on Slurm jobs. Namely the Jupyter Lab app was missing the first few lines which contains the token used for the application.

**Comment by xiroV** [comment]
After testing this over the last few days I have not been able to reproduce.

What I did in attempt to reproduce:
 - start >40 jobs in total (on slurm) on both dev and through the launcher,
 - tested different browsers (Chrome and Firefox),
 - tested SBatch app with various output, variables, hanging subcommands, etc.
 - Jupyter app on dev (which was mentioned in the bug report),
 - throttling network speed (Firefox).

**Comment by DanThrane** [comment]
I am closing this until we see a reproduction case again.
