### ISSUE TITLE
Introduce a way for users to stop an interactive app from inside the app

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3882]
Some users have requested the ability to send some kind of stop signal to a container from a script.

The use case is that they have been prototyping in an interactive session, and rather than having to restart the app with batch processing, they would like to run their job and have the app stop when it finishes.

JIRA reference: TICKET-1781

**Comment by emolinaro** [comment]
Any app can be stopped from command line. The correct command depends on the app. I am not sure this is a useful feature.
