### ISSUE TITLE
Notifications for shared folders take you to wrong page unless 'My Workspace' is selected

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3931]
![Screenshot from 2023-03-08 15-17-09](https://user-images.githubusercontent.com/44464613/223737081-deed8105-d801-4dc3-8ec9-ecf0526f90e7.png)

This is the page I land on when clicking the notification.

![Screenshot from 2023-03-08 15-18-00](https://user-images.githubusercontent.com/44464613/223736934-5e72d928-3997-47f6-bc4f-ebaf76f355d4.png)

Above is the page I expect to land on when clicking the notification.

**Comment by DanThrane** [comment]
Will be fixed in 2024.1.0
