### ISSUE TITLE
Admins of project cannot downgrade themself to the `USER` role

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#3993]
Within projects an admin cannot downgrade to userrole. It has the possiblity to downgrade all other user (except PI).

It makes it hard for PIs to transfer PI role and then become standard user

**Comment by Tiggles** [comment]
Also, make it a bit harder to downgrade, by modal, or something.

**Comment by Tiggles** [comment]
The modal approach has been implemented in the UI-redesign
