### ISSUE TITLE
Make it possible for users to change their contact emails.

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#3996]
We have a settings page and a email section, but users cannot change their contact mail themselves.
I suggest a update field on the settings page for users to write, verify and update to a new email.

We have a few users without any emails so it might be a good idea to have users check if their associated mail is correct as well as redirect them to the settings page if we do not recieve an email from WAYF on first login. 

No email = no support

**Comment by DanThrane** [comment]
Will be fixed with #4017
