### ISSUE TITLE
Pending icon for grant-applications makes it seem like a clickable dropdown menu

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3997]
![Screenshot from 2023-05-09 12-13-13](https://github.com/SDU-eScience/UCloud/assets/44464613/3e069d57-5520-4792-a85e-39f7eafb2c94)

In the grant application box the meatballs menu is not working. The only bit that can be clicked on is 'TESTING'.

**Comment by Tiggles** [comment]
It's because it's not a dropdown, it's meant as an "In progress" icon for GrantApplications. A terrible one, we definitely need a different one.

**Comment by Tiggles** [comment]
It should also be to the right, not where it's presented here.

**Comment by Tobias-V** [comment]
It stays on the right for the most parts, I had to resize my window to a weird resolution for it to move.

**Comment by Tiggles** [comment]
It seems to occur close to phone size for me.

**Comment by Tiggles** [comment]
Fixed with redesign
