### ISSUE TITLE
Insufficient funds while creating a drive/share in a personal workspace

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#4007]
Steps to reproduce:

1. Create a share or a drive in a  personal workspace
2. The backend replies with "Insufficient funds"

The issue has not been observed locally but is consistent in a production environment.

**Comment by hschu12** [comment]
Issue with check call attempting to do dryrun with "charge" of 1. However when user had a single allocation with negative value (both Henrik and Dan had a ceph allocation with -2 in localbalance) it would attempt to dry-charge all allocations resulting in charged ammount <= 0 and not 1 as expected for a succesfull "charge".
