### ISSUE TITLE
Frontend sends wrong info when browsing products from grant allocation page

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#4014]
When in a project and applying for more ressources to existing project, it always sends a request to browse the products of the grant giver with recieverType=personal_workspace and recipientId=null.

This results in being able to choose your parent project as grant giver, but not being able to see any products once selected due to permission error.

<img width="1481" alt="Screenshot 2023-06-12 at 09 53 42" src="https://github.com/SDU-eScience/UCloud/assets/10943804/bb8db596-67c0-477c-af37-397405ae1816">

**Comment by xiroV** [comment]
Possibly fixed in #4001.

**Comment by Tiggles** [comment]
This will also be fixed in ui-redesign because of the work @DanThrane is doing
