### ISSUE TITLE
UI-redesign issues

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#4033]
Current known issues:

- [x] Show reasoning why operation is disabled. Currently, they are hidden entirely.
- [x] Use new FileBrowser for file-selection
- [x] Modal file-browser has an unintended offset for the context-menu.
- [x] Disable drag to select on dashboard.
- [x] Inline operations (e.g. `Use`)
- [x] Sort by/Sort direction should be to the right
- [x] "Create..." color should be blue, and icon should be +
- [x] With enough elements, the uploader will start to show scrolling, but scrolls the wrong element
- [x] Ensure that provider icon is properly updated in FileBrowser URL (If bad reply from provider, it does not update)
- [x] MemberList: Reduce avatar and text size
- [x] MemberList: Header (inputfields etc.) should remain static on scroll
- [x] Missing icons for empty page (Resources)
- [x] News Edit/Preview should be clearly shown as something that can be clicked
- [x] Operations after confirmation buttons can't be selected/clicked
- [x] Public-link creation suffix/prefix missing
- [x] Pressing enter on a file should not try to open them as folders
- [x] Resource creation shows provider-icon, but shouldn't
- [x] Searching runs is missing
- [x] Searching for apps is missing
- [x]  FavIcons overlaps header for App Search and Tag search
- [x] Interactive applications are not opened in a new tab
- [x] ConfirmationButton doesn't show "Hold to Confirm" on single click
- [x] Dashboard has duplicate titles for cards
- [x] Add fancy graphics to dashboard news (Added, correct styling missing)
- [x] Missing context-switcher for project pages
- [x] Add logic to handle switching to personal workspace when viewing members or subprojects
- [x] It looks like drag & drop in the file browser no longer works correctly when attempting to drop to another row. The target icons lights up but the tooltip doesn't change. This bug does not appear to affect dropping to a breadcrumb. (Note: Seems like a `entryBelowCursorTemporary` is not correctly set. I think it's correctly set to the right value, then null twice.)
- [x] Resource allocation page appears to be broken. New targets cannot be created. Alignment is wrong. Font-sizes are inconsistent. Most input fields are invisible. 
- [x] Breadcrumbs in project management is broken.  (??? - Is this that they don't do anything?)
- [x] "View subprojects" on the subprojects page is broken.
- [x] Clicking on the sensitivity of a file row does nothing.
- [x] There is no button to start a new grant application.
- [x] There is no way to view the full path of a project. (Sidebar has the avatar-pop-out containing it)
- [x] Grant applications are incorrectly considered a consumable resource.
- [x] Consumeable Projects can be considered non-consumable if no project is in cache yet.
- [x] Renaming a resource to the same name will still submit the name and get a CONFLICT response
- [x] Activating Licenses shows nothing on clicking button
- [x] Going from non-consumable resource to consumable resource project will render both on dashboard
- [x] No jobs case does not use the blue circle with icons.
- [x] Terminal windows have a max-height, seems to be created on window opening
- [x] Context Switcher is missing in app store.
- [x] Grant Application editor needs some margin/padding at the top.
- [x] If a "Hold to confirm"-button is shown, the operations row is set to twice the size.
- [x] Tooltip continued to exist after file-selector was opened
- [x] "Copy to" uses the old file-selector
- [x] "Show member files" should be "View member files", also it's missing from drives
- [x] Clicking the checkbox fast can leave the view in an inconsistent state.
- [x] Disable Creating Drives if "View member files" is active
- [x] Missing syncthing integration
- [x] Job Results uses the old files table
- [x] Selecting machine type list on run app page should not multiply on price (Outsourced to Brian)
- [x] Disabled operations in contextMenu can still be reached using arrow-keys. Still not usable.
- [x] The arrow keys can be used to reach inner part of ConfirmAction-buttons
- [x] Breadcrumb navigation doesn't work when viewing job results
- [x] Folder creation is not working when viewing job results. Uploads are.
- [x] Accepting a project link redirects the user to a "Not found" page (/app/projects).
- [x] Grant applications appear to not track input state correctly. Submitting an applications always results in the following error message (and no RPC call is ever made): "At least one resource field must be non-zero."
- [x] Project invite links are invisible in modal (All input fields ignored `props.value`)
- [x] Old style selectors are still in use
- [x] File-selector
- [x] Job-selector
- [x] Changing drives in the file-selector is missing, and tabcomplete doesn't work, making some things impossible, including moving files from drive to drive.
- [x] Workspace search field does not automatically gain focus after opening the dialog:
- [x] Styling issue when accepting a project link
- [x] Missing children for alt-button group
- [x] SSH key always considered an unconsumable resource
- [x] Unconsumable resource text is destructively rendered.
- [x] Uploader is seriously broken, look-wise
- [x] Clicking the star on application search results do produce a request, but the UI is never updated.
- [x] Context menu shortcuts are not correctly incremented when ops follow op-groups
- [x] On the project members page, avatars are fetched in an infinite loop if no avatar is returned from the backend.
- [x] Default icon for app is not handled correctly for multiple of the same app. E.g. Syncthing
- [x] Wrong icon for SSH keys are used on browse page.
- [x] Double-clicking SSH key leads to create page
- [x] Reduce `ttl` for projectCache, to ensure correctness of ContextSwitcher content.
- [x] MemberList has an unintended cut-off in list.

Safari:

- [x] Clicking on a sidebar icon gives you a broken sidebar, that resolves itself after a few clicks.
- [x] Navigating to UCloud through `/app/login` sometimes fails to show sidebar. (Failing to reproduce)

If you find anything else that hasn't been reported or listed above, please explain the issue in a comment

**Comment by DanThrane** [comment]
It looks like drag & drop in file the browser no longer works correctly when attempting to drop to another row. The target icons lights up but the tooltip doesn't change. This bug does not appear to affect dropping to a breadcrumb.

**Comment by DanThrane** [comment]
Clicking on the files tab in Safari gives you a broken sidebar
<img width="1616" alt="image" src="https://github.com/SDU-eScience/UCloud/assets/1782437/9b191106-3868-49f5-a379-ab9a34c196dd">

**Comment by Tiggles** [comment]
It seems to fix itself after a few clicks/scrolls elsewhere, so maybe fewer events are fired in Safari.

**Comment by DanThrane** [comment]
Color use for disabled entries could be improved (perhaps by changing text color?). I would expect the entry to be skipped when using the arrow keys for navigation, but it appears to be selected. 
<img width="626" alt="image" src="https://github.com/SDU-eScience/UCloud/assets/1782437/a7157fab-afa2-447c-88e7-99a966dde27f">

**Comment by DanThrane** [comment]
Terminal no longer resizes correctly (I added a purple background on the `<body>` for clarity, the terminal is supposed to take up all of the space)
![image](https://github.com/SDU-eScience/UCloud/assets/1782437/608b4f6f-b29d-4407-9a24-e479cdedbfbb)

**Comment by DanThrane** [comment]
Old style selectors are used for most application resources that are not files. For example connecting to another job or adding a public IP:
<img width="1616" alt="image" src="https://github.com/SDU-eScience/UCloud/assets/1782437/28d4ffd8-7ef4-48c8-816b-cba162bb8e5f">

**Comment by DanThrane** [comment]
Navigation using breadcrumbs does not work on the job complete page (this used to open the file browser at the corresponding path):
<img width="1616" alt="image" src="https://github.com/SDU-eScience/UCloud/assets/1782437/dc48a83f-dacc-402d-a5d1-614cc04e64db">

**Comment by DanThrane** [comment]
Grant applications appear to not track input state correctly. Submitting an applications always results in the following error message (and no RPC call is ever made): "At least one resource field must be non-zero."

**Comment by DanThrane** [comment]
Missing grant application panel. I am not sure what triggers this, but I am on a new user (not admin) who is a normal member (not admin) of a normal project.
<img width="1616" alt="image" src="https://github.com/SDU-eScience/UCloud/assets/1782437/56ddaaaa-083b-48fc-a135-eb642adebc85">

**Comment by Tiggles** [comment]
For the missing grant applications, this is the same behavior as on the production system.

**Comment by DanThrane** [comment]
Trying to access an SSH key always results in the following. This should never happen regardless of the selected project since this resource is always personal to you (regardless of active project).

<img width="1616" alt="image" src="https://github.com/SDU-eScience/UCloud/assets/1782437/8fc853f3-462f-44d7-9198-0e00fc278eef">

**Comment by DanThrane** [comment]
Styling issue in "Upload files" dialog box
<img width="712" alt="image" src="https://github.com/SDU-eScience/UCloud/assets/1782437/aac477ca-d1c8-4bef-8392-5d0ae7c17adb">

**Comment by Tiggles** [comment]
Already in the list, fixed yesterday.

**Comment by DanThrane** [comment]
Right clicking in an empty folder (probably any folder) gives a broken context menu (two entries with [1], two entries with [2]). I think it would also make sense to just remove the "Add to sync" entry, we can just do it from the "Manage synchronization" entry. Either that or collapse the two in the top menu, at the moment we are using quite a lot of space just for showing buttons for synchronization.

<img width="1616" alt="image" src="https://github.com/SDU-eScience/UCloud/assets/1782437/8a7a9714-9585-4ef6-bbeb-8e9fdf171235">

**Comment by hschu12** [comment]
After creating subprojects from allocation page, the context switcher does not include my new project (of which I am PI) before a refresh . I can navigate between pages without it loading into the context switcher, but a refresh loads it.

**Comment by Tiggles** [comment]
Part 2 in #4050
