### ISSUE TITLE
BrowseSuballocations does not list all allocations within subproject

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#4047]
Reported by User.
Being admin of Type1 AAU and looking at allocations. In suballocations there is a project called "Testing Project for CLAAUDIA troubleshooting". When shown in full list with browse suballocation, allocations are missing e.g. uc-a100. However when search for using the frontend (searchSubAllocation) they are all listed in the response.

BrowseSuballocation returns 8 elements for this project
SearchSubAllocation returns 14 elements for this project

**Comment by DanThrane** [comment]
Fixed in 2024.1.0
