### ISSUE TITLE
Show a front-end notification when a job transitions to RUNNING

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#4089]
Always show, no matter the time it took.
But maybe don't show if already viewing the job.
No requirements for opting in.
Show across all projects?
Show on for person who started the job, or every job across all projects?
Only show for active project?
Play a sound on transition?

**Comment by Tiggles** [comment]
Companion issue #4088

**Comment by xiroV** [comment]
- Add "Completed" job state notification.
 - Try to aggregate emails and notifications (in case a user starts a lot of jobs).
