### ISSUE TITLE
Machines are listed even if there is no active allocations

### ISSUE THREAD

**Issue by xiroV** [SDU-eScience/UCloud#4112]
branch `dev-2024-1-0`

On create-job page, *Machine types* does not list products for which the user have no allocations, however it does list products if there is an allocation whether it's active or not. I.e. if the user have an allocation starting in the future, the products will be visible but not usable.

I'm unsure if this is intended or not, but I'm guessing products which are not usable shouldn't be visible.

In case this is intended, there is missing error-handling on the frontend for the error returned by the backend when the user tries to use a product when there's no active allocation. This should probably be handled either way.

**Comment by DanThrane** [comment]
Sounds like a bug to me.
