### ISSUE TITLE
Grant additional information changes

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#4220]
Depending if you create a new grant and if you look at the grant after creating it, the additional infomation boxes has changed and multiplied.

1. Create a grant application
2. Refresh the page

<img width="1130" alt="Screenshot 2024-05-23 at 13 13 41" src="https://github.com/SDU-eScience/UCloud/assets/10943804/a3137e8e-56ef-45ac-9aca-6ef78a2ba4be">
<img width="1131" alt="Screenshot 2024-05-23 at 13 13 57" src="https://github.com/SDU-eScience/UCloud/assets/10943804/cad33bd7-7634-4f53-b3f8-d1adf99895c6">

**Comment by Tiggles** [comment]
I could not reproduce by applying for resources for a new project and reloading the page.

**Comment by Tiggles** [comment]
Reproduced on `dev`:

1. apply for resources for existing project
2. add Type 1 for resources, and request some
3. Project title, abstract and description of the... is shown
4. Apply for resources
5. T1 and full abstract appears in addition to the others, no refresh needed

**Comment by Tiggles** [comment]
Seems to be that both `stateDuringCreate` and `stateDuringEdit` are `undefined`, so it's always a `newProject`
https://github.com/SDU-eScience/UCloud/blob/master/frontend-web/webclient/app/Grants/Editor.tsx#L225

**Comment by Tiggles** [comment]
Here are the reducer actions, and the state of `stateDuringCreate` and `stateDuringEdit`, respectively, after each state change. Seems to be out of order that is the issue.
<img width="1410" alt="Screenshot 2024-07-30 at 11 04 13" src="https://github.com/user-attachments/assets/dda65940-3291-4bd3-b897-49a5ff989733">
