### ISSUE TITLE
Table below usage over time has an incorrect "change" value

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#4232]
It looks like the change column no longer makes sense. It is almost certainly related to the change in order. It appears that numbers are subtracted from each other in the opposite order of what they should be.

**Comment by mrlhansen** [comment]
I still think this is not correct. In the last column, I would expect the change to reflect the change wrt. to line beneath (the previous entry). So on the first line the change should read +0,53 and the second line +14,10, etc. On the last line the change should be zero I guess.

**Comment by DanThrane** [comment]
I agree with Martin. Just to add to what he is saying I think the final missing piece is the fact that one line is actually missing from the table, which is how you get the `+4,47` in your screenshot. Without the last line that change cannot possible make any sense.

So I would probably try to:

- Add the current usage (which is already present, because otherwise you wouldn't be able to get `+4,47`)
- Shift the calculation by one as Martin is saying.

![image](https://github.com/SDU-eScience/UCloud/assets/1782437/e4e07338-e881-49e1-a31b-868ccfe392fe)

(There are some missing precision in my table, which is why the numbers don't match perfectly)

**Comment by Tiggles** [comment]
So like this?
<img width="643" alt="Screenshot 2024-05-29 at 09 38 47" src="https://github.com/SDU-eScience/UCloud/assets/7610257/cf68607c-0641-46e2-89e3-a246f2f42c4a">

**Comment by Tiggles** [comment]
This seems to match your numbers, with the addition of a new entry. Should we omit the +0.00, or just keep it for consistency?
![image](https://github.com/SDU-eScience/UCloud/assets/7610257/dafbe6bb-7b81-4233-aece-f6a0a89ddab6)
