### ISSUE TITLE
Allocation not active icon bit unclear in darkmode

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#4244]
Depending on your screen brightness it might be hard to see the calendar icon on the allocation page since it is also a little bit grayed out. 

<img width="1180" alt="Screenshot 2024-05-31 at 12 46 11" src="https://github.com/SDU-eScience/UCloud/assets/10943804/47cf24cb-695d-474f-9b90-77ef0f3a17a2">

**Comment by Tiggles** [comment]
Could this maybe be changed to an exclamation point icon or something? That way, that hovering is something you should do might be more clear.

**Comment by Tiggles** [comment]
Make the opacity rules specifically target everything OTHER than the calendar icon.

Before
<img width="122" alt="Screenshot 2024-06-04 at 16 05 11" src="https://github.com/SDU-eScience/UCloud/assets/7610257/23537054-2fbe-4e0b-9e62-6c47f45b719c">

After
<img width="162" alt="Screenshot 2024-06-04 at 16 04 05" src="https://github.com/SDU-eScience/UCloud/assets/7610257/71672804-e30a-46ed-8c9b-df1b5e9ba767">
