### ISSUE TITLE
UI bug in allocator view

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#4356]
See attached screenshot. The allocator is incorrectly seeing the bar in red, even though it shouldn't be. I don't even believe that this information is available to the allocator through this API, so this is probably just some simple bug in the rendering code.

The screenshot shows the allocator at the top and the recipient at the bottom. 
![image](https://github.com/user-attachments/assets/60fdb51d-adfa-4803-97e8-58077594a3f1)

**Comment by Tiggles** [comment]
The `limitPercentage` is a little bit off

<img width="310" alt="Screenshot 2024-08-07 at 12 22 10" src="https://github.com/user-attachments/assets/14864cea-
aff6-49ed-a9ba-2f05f1b4200d">

**Comment by Tiggles** [comment]
LimitPercentage is way off

<img width="310" alt="Screenshot 2024-08-07 at 12 22 10" src="https://github.com/user-attachments/assets/c0368916-d4de-4bc1-af3d-fab617c046a6">

**Comment by Tiggles** [comment]
The `maxUsable` is negative. Backend issue? AllocationId: 8904

<img width="236" alt="Screenshot 2024-08-07 at 12 55 43" src="https://github.com/user-attachments/assets/7bf2291f-084f-4411-8990-78264343f457">

**Comment by Tiggles** [comment]
Seems to come from this line
https://github.com/SDU-eScience/UCloud/blob/master/frontend-web/webclient/app/Accounting/Allocations.tsx#L681

`localUsage` is, as far as I can see, straight from the backend, `uq.quota` is calculated in the frontend.

**Comment by Tiggles** [comment]
Does `localUsage` need to be normalized with the `Accounting.combineBalances`? Or should it just be used directly as is?
