### ISSUE TITLE
Store file "clipboard" outside of the component

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#4360]
This should allow for copying & pasting files across component reloads. It does not have to be persistent across page reloads, but could be (maybe add a max age in that case).

**Comment by Tiggles** [comment]
Some things to maybe consider:

- Should the copy paste also allow to happen between modals and non-modal components (and vice versa)?
- When should it be removed from the clipboard? E.g. leaving a specific page, accessing specific pages, etc. (age already mentioned)

**Comment by DanThrane** [comment]
> Should the copy paste also allow to happen between modals and non-modal components (and vice versa)?

I don't see any reason why it shouldn't be allowed.

> When should it be removed from the clipboard? E.g. leaving a specific page, accessing specific pages, etc. (age already mentioned)

For a normal copy, I don't think it should unless overriden by a new copy. For cut it should disappear when pasted. We could consider a maximum life-time of a few minutes, but beyond that I don't think it should disappear for any reason related to the UI.

**Comment by Tiggles** [comment]
Good. I agree with both of these.

**Comment by Tiggles** [comment]
Is this considered finished with the feature flag in place? @DanThrane
