### ISSUE TITLE
[IM2] Unknown job registration registered the same job many times

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#4464]
Observed by Martin on the test Hippo cluster. The same job was registered a total of 2577 times. The job was submitted through UCloud, but was still registered as an unknown job. All generated provider IDs had the same registered Slurm ID and differed only in the "discovered at" timestamp. None of the jobs ever transitioned state despite the original job (created through UCloud) did transition state.

**Comment by xiroV** [comment]
Attempted to reproduce this in various ways, both in a local test environment and on sandbox, without luck. I'm thinking there might be an unhandled race condition somewhere. Will keep the issue open for now, in case the problem reappears.
