### ISSUE TITLE
Redesign of public link, public IP and drive creation

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#4477]
Switch from the current inline creator to a modal-based one (or full screen). This will also allow us to perform extra
configuration of the resource right away. This includes:

- Permissions
- Firewall for ingress
- Name for drives and links

Examples from other software:

![image](https://github.com/user-attachments/assets/9e10b1d5-3a1a-48cf-91bf-5d413f3f2fec)

**Comment by Tiggles** [comment]
- [ ] Permissions
- [ ] Firewall for ingress
- [ ] Name for drives and links
